const mockCompanies = [
  {
    id: 1,
    companyCode: "COMP001",
    companyName: "Tech Solutions Ltd",
    email: "info@techsolutions.com",
    telephone: "+94112345678",
    mobileSMS: "+94771234567",
    whatsapp: "+94771234567",
    mobile: "+94771234567",
    address: "123 Tech Park, Colombo 03",
    rsInvoiceCash: "RS001",
    creditRSInvoice: "CRS001",
    wsInvoiceCash: "WS001",
    creditWSInvoice: "CWS001",
    special: "None",
    withholdingTax: 5,
    crDaysCA: "30",
    cr: "A+",
    ssclRate: "2.5",
    orderNumber: "ORD001",
    srnNumber: "SRN001",
    currentYear: "2025",
    vat: "15%",
  },
  {
    id: 2,
    companyCode: "COMP002",
    companyName: "Global Trading Co",
    email: "info@globaltrading.com",
    telephone: "+94114567890",
    mobileSMS: "+94777890123",
    whatsapp: "+94777890123",
    mobile: "+94777890123",
    address: "456 Trade Center, Colombo 02",
    rsInvoiceCash: "RS002",
    creditRSInvoice: "CRS002",
    wsInvoiceCash: "WS002",
    creditWSInvoice: "CWS002",
    special: "Premium",
    withholdingTax: 8,
    crDaysCA: "45",
    cr: "A",
    ssclRate: "3.0",
    orderNumber: "ORD002",
    srnNumber: "SRN002",
    currentYear: "2025",
    vat: "15%",
  },
  {
    id: 3,
    companyCode: "COMP003",
    companyName: "Innovative Designs Inc",
    email: "contact@innodesigns.com",
    telephone: "+94116789012",
    mobileSMS: "+94778901234",
    whatsapp: "+94778901234",
    mobile: "+94778901234",
    address: "789 Design Street, Colombo 05",
    rsInvoiceCash: "RS003",
    creditRSInvoice: "CRS003",
    wsInvoiceCash: "WS003",
    creditWSInvoice: "CWS003",
    special: "Gold",
    withholdingTax: 10,
    crDaysCA: "60",
    cr: "A-",
    ssclRate: "3.5",
    orderNumber: "ORD003",
    srnNumber: "SRN003",
    currentYear: "2025",
    vat: "12%",
  },
  {
    id: 4,
    companyCode: "COMP004",
    companyName: "NextGen Enterprises",
    email: "support@nextgen.com",
    telephone: "+94119876543",
    mobileSMS: "+94776543210",
    whatsapp: "+94776543210",
    mobile: "+94776543210",
    address: "321 Future Lane, Colombo 07",
    rsInvoiceCash: "RS004",
    creditRSInvoice: "CRS004",
    wsInvoiceCash: "WS004",
    creditWSInvoice: "CWS004",
    special: "Silver",
    withholdingTax: 7,
    crDaysCA: "40",
    cr: "B+",
    ssclRate: "2.8",
    orderNumber: "ORD004",
    srnNumber: "SRN004",
    currentYear: "2025",
    vat: "10%",
  },
  {
    id: 5,
    companyCode: "COMP005",
    companyName: "Eco Friendly Solutions",
    email: "hello@eco-solutions.com",
    telephone: "+94112349876",
    mobileSMS: "+94771239876",
    whatsapp: "+94771239876",
    mobile: "+94771239876",
    address: "654 Green Avenue, Colombo 06",
    rsInvoiceCash: "RS005",
    creditRSInvoice: "CRS005",
    wsInvoiceCash: "WS005",
    creditWSInvoice: "CWS005",
    special: "Eco",
    withholdingTax: 6,
    crDaysCA: "50",
    cr: "B",
    ssclRate: "3.2",
    orderNumber: "ORD005",
    srnNumber: "SRN005",
    currentYear: "2025",
    vat: "14%",
  },
  {
    id: 6,
    companyCode: "COMP006",
    companyName: "Alpha Tech Corp",
    email: "contact@alphatech.com",
    telephone: "+94111234567",
    mobileSMS: "+94771234567",
    whatsapp: "+94771234567",
    mobile: "+94771234567",
    address: "123 Alpha Street, Colombo 01",
    rsInvoiceCash: "RS006",
    creditRSInvoice: "CRS006",
    wsInvoiceCash: "WS006",
    creditWSInvoice: "CWS006",
    special: "Platinum",
    withholdingTax: 9,
    crDaysCA: "35",
    cr: "A+",
    ssclRate: "2.7",
    orderNumber: "ORD006",
    srnNumber: "SRN006",
    currentYear: "2025",
    vat: "13%",
  },
  {
    id: 7,
    companyCode: "COMP007",
    companyName: "Beta Innovations",
    email: "info@betainnovations.com",
    telephone: "+94113456789",
    mobileSMS: "+94773456789",
    whatsapp: "+94773456789",
    mobile: "+94773456789",
    address: "456 Beta Avenue, Colombo 04",
    rsInvoiceCash: "RS007",
    creditRSInvoice: "CRS007",
    wsInvoiceCash: "WS007",
    creditWSInvoice: "CWS007",
    special: "Standard",
    withholdingTax: 4,
    crDaysCA: "25",
    cr: "B+",
    ssclRate: "2.3",
    orderNumber: "ORD007",
    srnNumber: "SRN007",
    currentYear: "2025",
    vat: "11%",
  },
  {
    id: 8,
    companyCode: "COMP008",
    companyName: "Gamma Enterprises",
    email: "support@gamma.com",
    telephone: "+94114567890",
    mobileSMS: "+94774567890",
    whatsapp: "+94774567890",
    mobile: "+94774567890",
    address: "789 Gamma Road, Colombo 08",
    rsInvoiceCash: "RS008",
    creditRSInvoice: "CRS008",
    wsInvoiceCash: "WS008",
    creditWSInvoice: "CWS008",
    special: "Bronze",
    withholdingTax: 3,
    crDaysCA: "20",
    cr: "C",
    ssclRate: "2.0",
    orderNumber: "ORD008",
    srnNumber: "SRN008",
    currentYear: "2025",
    vat: "9%",
  },
  {
    id: 9,
    companyCode: "COMP009",
    companyName: "Delta Solutions",
    email: "hello@deltasolutions.com",
    telephone: "+94115678901",
    mobileSMS: "+94775678901",
    whatsapp: "+94775678901",
    mobile: "+94775678901",
    address: "321 Delta Lane, Colombo 09",
    rsInvoiceCash: "RS009",
    creditRSInvoice: "CRS009",
    wsInvoiceCash: "WS009",
    creditWSInvoice: "CWS009",
    special: "Diamond",
    withholdingTax: 12,
    crDaysCA: "55",
    cr: "A",
    ssclRate: "3.8",
    orderNumber: "ORD009",
    srnNumber: "SRN009",
    currentYear: "2025",
    vat: "16%",
  },
  {
    id: 10,
    companyCode: "COMP010",
    companyName: "Omega Industries",
    email: "contact@omegaindustries.com",
    telephone: "+94116789012",
    mobileSMS: "+94776789012",
    whatsapp: "+94776789012",
    mobile: "+94776789012",
    address: "654 Omega Street, Colombo 10",
    rsInvoiceCash: "RS010",
    creditRSInvoice: "CRS010",
    wsInvoiceCash: "WS010",
    creditWSInvoice: "CWS010",
    special: "Elite",
    withholdingTax: 15,
    crDaysCA: "65",
    cr: "A+",
    ssclRate: "4.0",
    orderNumber: "ORD010",
    srnNumber: "SRN010",
    currentYear: "2025",
    vat: "18%",
  },
];

const mockCustomers = [
  {
    id: 1,
    customerCode: "CUST001",
    customerName: "Royal Auto Center",
    type: "D-Customer",
    vatNumber: 123456789,
    nic: "782345671V",
    withHoldingTax: 5,
    businessRegistrationNo: "BUS78901234",
    owner: "Sunil Perera",
    auto: true,
    mobilePhone: "+94771234567",
    telephone: "+94112345678",
    email: "info@royalauto.lk",
    contactPerson: "Ajith Fernando",
    areaCode: "COL-01",
    district: "Colombo",
    city: "Colombo 3",
    customerAddress: "123 Galle Road, Colombo 3, Sri Lanka",
    creditLimit: 500000,
    colomboArea: 1,
    crColomboCash: 30000,
    discount: 5,
    colomboCash: 25000,
    colomboCredit: 150000,
    outstationCash: 15000,
    outstationCredit: 80000,
    annualTarget: 2500000,
    accountCode1: "AC12345",
    bankCode1: "BOC001",
    accountCode2: "AC67890",
    bankCode2: "SAMP002",
    accountCode3: "",
    bankCode3: "",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Both",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "2005",
    fieldOfBusiness: "Automobile Repair",
    driverCode: "DRV01",
    transportAgent: "Express Delivery",
    dueDays: 30,
    whatsapp: "+94771234567",
    mobile: "+94771234568",
    salesman: "Chaminda Silva",
    remarks: "Loyal customer since 2005, prefers branded parts only.",
  },
  {
    id: 2,
    customerCode: "CUST002",
    customerName: "Lanka Motors",
    type: "D-Customer",
    vatNumber: 234567890,
    nic: "652345678V",
    withHoldingTax: 3,
    businessRegistrationNo: "BUS12345678",
    owner: "Nimal Gunawardena",
    auto: false,
    mobilePhone: "+94772345678",
    telephone: "+94112345679",
    email: "contact@lankamotors.com",
    contactPerson: "Saman Perera",
    areaCode: "COL-02",
    district: "Colombo",
    city: "Colombo 5",
    customerAddress: "456 Havelock Road, Colombo 5, Sri Lanka",
    creditLimit: 750000,
    colomboArea: 1,
    crColomboCash: 50000,
    discount: 7,
    colomboCash: 40000,
    colomboCredit: 250000,
    outstationCash: 0,
    outstationCredit: 0,
    annualTarget: 3500000,
    accountCode1: "AC23456",
    bankCode1: "COM003",
    accountCode2: "",
    bankCode2: "",
    accountCode3: "",
    bankCode3: "",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Credit",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "1998",
    fieldOfBusiness: "Vehicle Service Center",
    driverCode: "DRV02",
    transportAgent: "Quick Delivery",
    dueDays: 45,
    whatsapp: "+94772345678",
    mobile: "+94772345679",
    salesman: "Lasith Malinga",
    remarks: "Specializes in Japanese vehicles, bulk orders monthly.",
  },
  {
    id: 3,
    customerCode: "CUST003",
    customerName: "Supreme Auto Parts",
    type: "D-Supplier",
    vatNumber: 345678901,
    nic: "723456789V",
    withHoldingTax: 8,
    businessRegistrationNo: "BUS23456789",
    owner: "Asela Samaraweera",
    auto: true,
    mobilePhone: "+94773456789",
    telephone: "+94113456789",
    email: "orders@supremeauto.lk",
    contactPerson: "Kumara Sangakkara",
    areaCode: "KDY-01",
    district: "Kandy",
    city: "Kandy",
    customerAddress: "78 Peradeniya Road, Kandy, Sri Lanka",
    creditLimit: 1000000,
    colomboArea: 0,
    crColomboCash: 0,
    discount: 10,
    colomboCash: 0,
    colomboCredit: 0,
    outstationCash: 80000,
    outstationCredit: 350000,
    annualTarget: 4000000,
    accountCode1: "AC34567",
    bankCode1: "HNB004",
    accountCode2: "AC78901",
    bankCode2: "NSB005",
    accountCode3: "AC23456",
    bankCode3: "PB006",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Both",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "2010",
    fieldOfBusiness: "Auto Parts Retail",
    driverCode: "DRV03",
    transportAgent: "Central Logistics",
    dueDays: 60,
    whatsapp: "+94773456790",
    mobile: "+94773456791",
    salesman: "Mahela Jayawardene",
    remarks: "Purchases heavy machinery parts, requires special handling.",
  },
  {
    id: 4,
    customerCode: "CUST004",
    customerName: "Elite Car Care",
    type: "D-Customer",
    vatNumber: 456789012,
    nic: "834567890V",
    withHoldingTax: 5,
    businessRegistrationNo: "BUS34567890",
    owner: "Dinesh Chandimal",
    auto: false,
    mobilePhone: "+94774567890",
    telephone: "+94114567890",
    email: "service@elitecarcare.com",
    contactPerson: "Angelo Mathews",
    areaCode: "GAL-01",
    district: "Galle",
    city: "Galle",
    customerAddress: "23 Fort Road, Galle, Sri Lanka",
    creditLimit: 300000,
    colomboArea: 0,
    crColomboCash: 0,
    discount: 4,
    colomboCash: 0,
    colomboCredit: 0,
    outstationCash: 35000,
    outstationCredit: 120000,
    annualTarget: 1500000,
    accountCode1: "AC45678",
    bankCode1: "SAMP007",
    accountCode2: "",
    bankCode2: "",
    accountCode3: "",
    bankCode3: "",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Credit",
    printInvoiceDetail: "No",
    alwaysPending: "No",
    yearOfEstablishment: "2015",
    fieldOfBusiness: "Luxury Vehicle Maintenance",
    driverCode: "DRV04",
    transportAgent: "Southern Express",
    dueDays: 30,
    whatsapp: "+94774567891",
    mobile: "+94774567892",
    salesman: "Thisara Perera",
    remarks: "Specializes in luxury European vehicles.",
  },
  {
    id: 5,
    customerCode: "CUST005",
    customerName: "Quick Fix Garage",
    type: "D-Customer",
    vatNumber: 567890123,
    nic: "695678901V",
    withHoldingTax: 2,
    businessRegistrationNo: "BUS45678901",
    owner: "Rangana Herath",
    auto: true,
    mobilePhone: "+94775678901",
    telephone: "+94115678901",
    email: "repairs@quickfix.lk",
    contactPerson: "Nuwan Kulasekara",
    areaCode: "COL-03",
    district: "Colombo",
    city: "Colombo 10",
    customerAddress: "45 Maradana Road, Colombo 10, Sri Lanka",
    creditLimit: 200000,
    colomboArea: 1,
    crColomboCash: 20000,
    discount: 3,
    colomboCash: 30000,
    colomboCredit: 80000,
    outstationCash: 0,
    outstationCredit: 0,
    annualTarget: 1200000,
    accountCode1: "AC56789",
    bankCode1: "BOC008",
    accountCode2: "AC90123",
    bankCode2: "COM009",
    accountCode3: "",
    bankCode3: "",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Both",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "2012",
    fieldOfBusiness: "Quick Repair Service",
    driverCode: "DRV05",
    transportAgent: "Rapid Delivery",
    dueDays: 15,
    whatsapp: "+94775678902",
    mobile: "+94775678903",
    salesman: "Upul Tharanga",
    remarks: "Specializes in quick repairs and emergency services.",
  },
  {
    id: 6,
    customerCode: "CUST006",
    customerName: "Island Auto Imports",
    type: "D-Supplier",
    vatNumber: 678901234,
    nic: "756789012V",
    withHoldingTax: 10,
    businessRegistrationNo: "BUS56789012",
    owner: "Tillakaratne Dilshan",
    auto: false,
    mobilePhone: "+94776789012",
    telephone: "+94116789012",
    email: "imports@islandauto.com",
    contactPerson: "Muttiah Muralitharan",
    areaCode: "COL-04",
    district: "Colombo",
    city: "Colombo 4",
    customerAddress: "67 Marine Drive, Colombo 4, Sri Lanka",
    creditLimit: 2000000,
    colomboArea: 1,
    crColomboCash: 100000,
    discount: 12,
    colomboCash: 150000,
    colomboCredit: 750000,
    outstationCash: 0,
    outstationCredit: 0,
    annualTarget: 10000000,
    accountCode1: "AC67890",
    bankCode1: "HNB010",
    accountCode2: "AC01234",
    bankCode2: "COM011",
    accountCode3: "AC45678",
    bankCode3: "NDB012",
    accountCode4: "AC89012",
    bankCode4: "BOC013",
    status: "Active",
    customerType: "Both",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "2000",
    fieldOfBusiness: "Automotive Import",
    driverCode: "DRV06",
    transportAgent: "Port Express",
    dueDays: 90,
    whatsapp: "+94776789013",
    mobile: "+94776789014",
    salesman: "Sanath Jayasuriya",
    remarks: "Major importer with exclusive dealerships for European parts.",
  },
  {
    id: 7,
    customerCode: "CUST007",
    customerName: "Precision Auto Engineering",
    type: "D-Customer",
    vatNumber: 789012345,
    nic: "787890123V",
    withHoldingTax: 5,
    businessRegistrationNo: "BUS67890123",
    owner: "Marvan Atapattu",
    auto: true,
    mobilePhone: "+94777890123",
    telephone: "+94117890123",
    email: "engineering@precisionauto.lk",
    contactPerson: "Chaminda Vaas",
    areaCode: "KUL-01",
    district: "Kurunegala",
    city: "Kurunegala",
    customerAddress: "34 Kandy Road, Kurunegala, Sri Lanka",
    creditLimit: 450000,
    colomboArea: 0,
    crColomboCash: 0,
    discount: 6,
    colomboCash: 0,
    colomboCredit: 0,
    outstationCash: 45000,
    outstationCredit: 180000,
    annualTarget: 2000000,
    accountCode1: "AC78901",
    bankCode1: "PB014",
    accountCode2: "",
    bankCode2: "",
    accountCode3: "",
    bankCode3: "",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Credit",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "2008",
    fieldOfBusiness: "Custom Engineering",
    driverCode: "DRV07",
    transportAgent: "Northwest Logistics",
    dueDays: 45,
    whatsapp: "+94777890124",
    mobile: "+94777890125",
    salesman: "Roshan Mahanama",
    remarks: "Specializes in custom engineering solutions and modifications.",
  },
  {
    id: 8,
    customerCode: "CUST008",
    customerName: "Green Light Motors",
    type: "D-Customer",
    vatNumber: 890123456,
    nic: "618901234V",
    withHoldingTax: 4,
    businessRegistrationNo: "BUS78901234",
    owner: "Arjuna Ranatunga",
    auto: false,
    mobilePhone: "+94778901234",
    telephone: "+94118901234",
    email: "service@greenlightmotors.com",
    contactPerson: "Aravinda de Silva",
    areaCode: "MTR-01",
    district: "Matara",
    city: "Matara",
    customerAddress: "56 Beach Road, Matara, Sri Lanka",
    creditLimit: 350000,
    colomboArea: 0,
    crColomboCash: 0,
    discount: 5,
    colomboCash: 0,
    colomboCredit: 0,
    outstationCash: 40000,
    outstationCredit: 150000,
    annualTarget: 1800000,
    accountCode1: "AC89012",
    bankCode1: "NDB015",
    accountCode2: "AC23456",
    bankCode2: "HNB016",
    accountCode3: "",
    bankCode3: "",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Both",
    printInvoiceDetail: "No",
    alwaysPending: "No",
    yearOfEstablishment: "2011",
    fieldOfBusiness: "Eco-friendly Vehicle Service",
    driverCode: "DRV08",
    transportAgent: "Southern Routes",
    dueDays: 30,
    whatsapp: "+94778901235",
    mobile: "+94778901236",
    salesman: "Romesh Kaluwitharana",
    remarks: "Focuses on eco-friendly vehicles and electric car maintenance.",
  },
  {
    id: 9,
    customerCode: "CUST009",
    customerName: "Highway Truck Services",
    type: "D-Customer",
    vatNumber: 901234567,
    nic: "729012345V",
    withHoldingTax: 6,
    businessRegistrationNo: "BUS89012345",
    owner: "Pramodya Wickramasinghe",
    auto: true,
    mobilePhone: "+94779012345",
    telephone: "+94119012345",
    email: "support@highwaytrucks.lk",
    contactPerson: "Hashan Tillakaratne",
    areaCode: "RAT-01",
    district: "Ratnapura",
    city: "Ratnapura",
    customerAddress: "89 Main Street, Ratnapura, Sri Lanka",
    creditLimit: 800000,
    colomboArea: 0,
    crColomboCash: 0,
    discount: 8,
    colomboCash: 0,
    colomboCredit: 0,
    outstationCash: 70000,
    outstationCredit: 400000,
    annualTarget: 5000000,
    accountCode1: "AC90123",
    bankCode1: "BOC017",
    accountCode2: "AC34567",
    bankCode2: "COM018",
    accountCode3: "AC78901",
    bankCode3: "SAMP019",
    accountCode4: "",
    bankCode4: "",
    status: "Active",
    customerType: "Credit",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "2007",
    fieldOfBusiness: "Heavy Vehicle Repair",
    driverCode: "DRV09",
    transportAgent: "Central Freight",
    dueDays: 75,
    whatsapp: "+94779012346",
    mobile: "+94779012347",
    salesman: "Russel Arnold",
    remarks: "Specializes in heavy trucks and commercial vehicles.",
  },
  {
    id: 10,
    customerCode: "CUST010",
    customerName: "Capital City Automobiles",
    type: "D-Supplier",
    vatNumber: 12345678,
    nic: "650123456V",
    withHoldingTax: 7,
    businessRegistrationNo: "BUS90123456",
    owner: "Kumar Sangakkara",
    auto: false,
    mobilePhone: "+94770123456",
    telephone: "+94110123456",
    email: "info@capitalcityauto.com",
    contactPerson: "Mahela Jayawardene",
    areaCode: "COL-05",
    district: "Colombo",
    city: "Colombo 7",
    customerAddress: "123 Reid Avenue, Colombo 7, Sri Lanka",
    creditLimit: 1500000,
    colomboArea: 1,
    crColomboCash: 80000,
    discount: 15,
    colomboCash: 100000,
    colomboCredit: 600000,
    outstationCash: 0,
    outstationCredit: 0,
    annualTarget: 8000000,
    accountCode1: "AC01234",
    bankCode1: "NDB020",
    accountCode2: "AC45678",
    bankCode2: "BOC021",
    accountCode3: "AC89012",
    bankCode3: "HNB022",
    accountCode4: "AC23456",
    bankCode4: "COM023",
    status: "Active",
    customerType: "Both",
    printInvoiceDetail: "Yes",
    alwaysPending: "No",
    yearOfEstablishment: "2003",
    fieldOfBusiness: "Luxury Automobile Sales",
    driverCode: "DRV10",
    transportAgent: "Premium Logistics",
    dueDays: 60,
    whatsapp: "+94770123457",
    mobile: "+94770123458",
    salesman: "Marvan Atapattu",
    remarks: "Premium dealer with focus on luxury vehicles and high-end parts.",
  },
];

const mockSuppliers = [
  {
    id: 1,
    supplierCode: "SUP001",
    supplierName: "AutoParts Global",
    supplierType: "dSupplier",
    foreignLocalSupplier: "foreign",
    address: "123 Auto Plaza, Singapore 384583",
    telephone: "+6599123456",
    whatsapp: "+6599123456",
    email: "orders@autopartsglobal.com",
    mobilePhone: "+6599123457",
    mobileSMS: "+6599123458",
    contactPerson: "John Lim",
    creditLimit: 50000,
    creditBalance: 35000,
    balanceBF: 15000,
    turnonver: 120000,
    srAmount: 5000,
    cifAmount: 95000,
    bankDetails: "OCBC Bank\nAccount: 123-45678-9\nSwift: OCBCSGSG",
  },
  {
    id: 2,
    supplierCode: "SUP002",
    supplierName: "Lanka Auto Supplies",
    supplierType: "dSupplier",
    foreignLocalSupplier: "local",
    address: "456 Peradeniya Road, Kandy, Sri Lanka",
    telephone: "+94812345678",
    whatsapp: "+94772345678",
    email: "sales@lankautos.lk",
    mobilePhone: "+94772345679",
    mobileSMS: "+94772345680",
    contactPerson: "Saman Perera",
    creditLimit: 25000,
    creditBalance: 10000,
    balanceBF: 5000,
    turnonver: 75000,
    srAmount: 3000,
    cifAmount: 0,
    bankDetails: "Commercial Bank\nAccount: 7654-3210\nBranch: Kandy",
  },
  {
    id: 3,
    supplierCode: "SUP003",
    supplierName: "Tokyo Motor Parts",
    supplierType: "dSupplier",
    foreignLocalSupplier: "foreign",
    address: "1-2-3 Shibuya, Tokyo, Japan",
    telephone: "+81345678901",
    whatsapp: "+81987654321",
    email: "export@tokyomotor.jp",
    mobilePhone: "+81345678902",
    mobileSMS: "+81345678903",
    contactPerson: "Akira Tanaka",
    creditLimit: 75000,
    creditBalance: 50000,
    balanceBF: 25000,
    turnonver: 180000,
    srAmount: 8000,
    cifAmount: 142000,
    bankDetails: "Mizuho Bank\nAccount: JP12345678901234\nSwift: MHCBJPJT",
  },
  {
    id: 4,
    supplierCode: "SUP004",
    supplierName: "Premium Motors PLC",
    supplierType: "dCustomer",
    foreignLocalSupplier: "local",
    address: "789 Galle Road, Colombo 03, Sri Lanka",
    telephone: "+94112345678",
    whatsapp: "+94772345681",
    email: "info@premiummotors.lk",
    mobilePhone: "+94772345682",
    mobileSMS: "+94772345683",
    contactPerson: "Nimal Fernando",
    creditLimit: 35000,
    creditBalance: 28000,
    balanceBF: 7000,
    turnonver: 95000,
    srAmount: 4500,
    cifAmount: 0,
    bankDetails: "Sampath Bank\nAccount: 100-5678-3421\nBranch: Colombo",
  },
  {
    id: 5,
    supplierCode: "SUP005",
    supplierName: "German Auto Exports",
    supplierType: "dSupplier",
    foreignLocalSupplier: "foreign",
    address: "Industriestrasse 123, Munich, Germany",
    telephone: "+4989123456",
    whatsapp: "+4917612345678",
    email: "sales@germanauto.de",
    mobilePhone: "+4917612345679",
    mobileSMS: "+4917612345680",
    contactPerson: "Hans Schmidt",
    creditLimit: 100000,
    creditBalance: 65000,
    balanceBF: 35000,
    turnonver: 250000,
    srAmount: 12000,
    cifAmount: 198000,
    bankDetails:
      "Deutsche Bank\nIBAN: DE89 3704 0044 0532 0130 00\nBIC: DEUTDEDBXXX",
  },
  {
    id: 6,
    supplierCode: "SUP006",
    supplierName: "Colombo Spare Parts",
    supplierType: "dSupplier",
    foreignLocalSupplier: "local",
    address: "45/2 Baseline Road, Colombo 08, Sri Lanka",
    telephone: "+94113456789",
    whatsapp: "+94773456789",
    email: "orders@colomboparts.lk",
    mobilePhone: "+94773456790",
    mobileSMS: "+94773456791",
    contactPerson: "Kumara Ratnayake",
    creditLimit: 15000,
    creditBalance: 8000,
    balanceBF: 7000,
    turnonver: 45000,
    srAmount: 2500,
    cifAmount: 0,
    bankDetails: "HNB Bank\nAccount: 002-054321-001\nBranch: Colombo",
  },
  {
    id: 7,
    supplierCode: "SUP007",
    supplierName: "Malaysian Auto Components",
    supplierType: "dSupplier",
    foreignLocalSupplier: "foreign",
    address: "Lot 123, Jalan Industri 5, Penang, Malaysia",
    telephone: "+6045678901",
    whatsapp: "+60123456789",
    email: "exports@malayauto.my",
    mobilePhone: "+60123456790",
    mobileSMS: "+60123456791",
    contactPerson: "Ahmad Razak",
    creditLimit: 40000,
    creditBalance: 25000,
    balanceBF: 15000,
    turnonver: 110000,
    srAmount: 5500,
    cifAmount: 87000,
    bankDetails: "Maybank\nAccount: 514-253698-102\nSwift: MBBEMYKL",
  },
  {
    id: 8,
    supplierCode: "SUP008",
    supplierName: "Luxury Vehicle Services",
    supplierType: "dCustomer",
    foreignLocalSupplier: "local",
    address: "123/7 Union Place, Colombo 02, Sri Lanka",
    telephone: "+94112345987",
    whatsapp: "+94772345987",
    email: "service@luxuryvehicle.lk",
    mobilePhone: "+94772345988",
    mobileSMS: "+94772345989",
    contactPerson: "Dilan Jayawardena",
    creditLimit: 20000,
    creditBalance: 12000,
    balanceBF: 8000,
    turnonver: 65000,
    srAmount: 3200,
    cifAmount: 0,
    bankDetails: "NDB Bank\nAccount: 101-23456-78\nBranch: Colombo",
  },
  {
    id: 9,
    supplierCode: "SUP009",
    supplierName: "Korean Auto Tech",
    supplierType: "dSupplier",
    foreignLocalSupplier: "foreign",
    address: "123-45 Gangnam-daero, Seoul, South Korea",
    telephone: "+8223456789",
    whatsapp: "+821023456789",
    email: "export@koreautotech.kr",
    mobilePhone: "+821023456790",
    mobileSMS: "+821023456791",
    contactPerson: "Park Ji-sung",
    creditLimit: 60000,
    creditBalance: 45000,
    balanceBF: 15000,
    turnonver: 135000,
    srAmount: 7000,
    cifAmount: 110000,
    bankDetails: "Shinhan Bank\nAccount: KR12 3456 7890 1234\nSwift: SHBKKRSE",
  },
  {
    id: 10,
    supplierCode: "SUP010",
    supplierName: "Galle Auto Traders",
    supplierType: "dCustomer",
    foreignLocalSupplier: "local",
    address: "78 Lighthouse Street, Galle, Sri Lanka",
    telephone: "+94912345678",
    whatsapp: "+94772345990",
    email: "sales@galleauto.lk",
    mobilePhone: "+94772345991",
    mobileSMS: "+94772345992",
    contactPerson: "Lasith Mendis",
    creditLimit: 18000,
    creditBalance: 10000,
    balanceBF: 8000,
    turnonver: 55000,
    srAmount: 2800,
    cifAmount: 0,
    bankDetails: "BOC\nAccount: 8901-234567-01\nBranch: Galle",
  },
];

const mockBanks = [
  {
    id: 1,
    bankCode: "BOC001",
    bankName: "Bank of Ceylon",
    branchCode: "BOC-HO",
    branchName: "Head Office",
    swiftCode: "BCEYLKLX",
    address: "No. 1, Bank of Ceylon Mawatha, Colombo 01, Sri Lanka",
    telephone: "+94112446790",
    mobilePhone: "+94771234567",
    contactName: "Ajith Fernando",
    email: "info@boc.lk",
    fax: "+94112321160",
    bankCEOName: "K.E.D. Sumanasiri",
  },
  {
    id: 2,
    bankCode: "SAMP002",
    bankName: "Sampath Bank PLC",
    branchCode: "SAMP-HO",
    branchName: "Head Office",
    swiftCode: "SAMPLKLX",
    address: "110, Sir James Peiris Mawatha, Colombo 02, Sri Lanka",
    telephone: "+94112300300",
    mobilePhone: "+94772345678",
    contactName: "Lakshman Perera",
    email: "info@sampathbank.lk",
    fax: "+94112300046",
    bankCEOName: "Nanda Fernando",
  },
  {
    id: 3,
    bankCode: "COM003",
    bankName: "Commercial Bank of Ceylon",
    branchCode: "COM-HO",
    branchName: "Head Office",
    swiftCode: "CCEYLKLX",
    address:
      "Commercial House, 21, Sir Razik Fareed Mawatha, Colombo 01, Sri Lanka",
    telephone: "+94112445010",
    mobilePhone: "+94773456789",
    contactName: "Sumith Karunaratne",
    email: "info@combank.lk",
    fax: "+94112449889",
    bankCEOName: "S. Renganathan",
  },
  {
    id: 4,
    bankCode: "HNB004",
    bankName: "Hatton National Bank",
    branchCode: "HNB-HO",
    branchName: "Head Office",
    swiftCode: "HBLILKLX",
    address: "HNB Towers, 479, T.B. Jayah Mawatha, Colombo 10, Sri Lanka",
    telephone: "+94112664664",
    mobilePhone: "+94774567890",
    contactName: "Priyantha Seneviratne",
    email: "info@hnb.lk",
    fax: "+94112662832",
    bankCEOName: "Jonathan Alles",
  },
  {
    id: 5,
    bankCode: "NSB005",
    bankName: "National Savings Bank",
    branchCode: "NSB-HO",
    branchName: "Head Office",
    swiftCode: "NSBALKLX",
    address: "255, Galle Road, Colombo 03, Sri Lanka",
    telephone: "+94112573008",
    mobilePhone: "+94775678901",
    contactName: "Chaminda Silva",
    email: "info@nsb.lk",
    fax: "+94112573178",
    bankCEOName: "Ajith Peiris",
  },
  {
    id: 6,
    bankCode: "PB006",
    bankName: "People's Bank",
    branchCode: "PB-HO",
    branchName: "Head Office",
    swiftCode: "PSBKLKLX",
    address: "75, Sir Chittampalam A Gardiner Mawatha, Colombo 02, Sri Lanka",
    telephone: "+94112327841",
    mobilePhone: "+94776789012",
    contactName: "Sunil Jayawardena",
    email: "info@peoplesbank.lk",
    fax: "+94112544095",
    bankCEOName: "Ranjith Kodituwakku",
  },
  {
    id: 7,
    bankCode: "SEYB007",
    bankName: "Seylan Bank PLC",
    branchCode: "SEYB-HO",
    branchName: "Head Office",
    swiftCode: "SEYBLKLX",
    address: "Level 15, Seylan Towers, 90, Galle Road, Colombo 03, Sri Lanka",
    telephone: "+94112456000",
    mobilePhone: "+94777890123",
    contactName: "Rohan Perera",
    email: "info@seylan.lk",
    fax: "+94112452584",
    bankCEOName: "Kapila Ariyaratne",
  },
  {
    id: 8,
    bankCode: "NDB008",
    bankName: "National Development Bank",
    branchCode: "NDB-HO",
    branchName: "Head Office",
    swiftCode: "NDBSLKLX",
    address: "40, Nawam Mawatha, Colombo 02, Sri Lanka",
    telephone: "+94112448888",
    mobilePhone: "+94778901234",
    contactName: "Anil Gunawardena",
    email: "info@ndbbank.com",
    fax: "+94112341044",
    bankCEOName: "Dimantha Seneviratne",
  },
  {
    id: 9,
    bankCode: "DFCC009",
    bankName: "DFCC Bank",
    branchCode: "DFCC-HO",
    branchName: "Head Office",
    swiftCode: "DFCCLKLX",
    address: "73/5, Galle Road, Colombo 03, Sri Lanka",
    telephone: "+94112442442",
    mobilePhone: "+94779012345",
    contactName: "Nihal Jayawardene",
    email: "info@dfccbank.com",
    fax: "+94112440376",
    bankCEOName: "Lakshman Silva",
  },
  {
    id: 10,
    bankCode: "PABC010",
    bankName: "Pan Asia Banking Corporation",
    branchCode: "PABC-HO",
    branchName: "Head Office",
    swiftCode: "PABSLKLX",
    address: "450, Galle Road, Colombo 03, Sri Lanka",
    telephone: "+94114667777",
    mobilePhone: "+94770123456",
    contactName: "Lalith Fonseka",
    email: "info@pabcbank.com",
    fax: "+94114740588",
    bankCEOName: "Nimal Tillekeratne",
  },
];

const mockBranches = [
  {
    id: 1,
    branchCode: "BOC-COL1",
    branchName: "Bank of Ceylon - Colombo Main",
    bankCode: "BOC001",
    bankCEO: "K.E.D. Sumanasiri",
    city: "Colombo 01",
    district: "Colombo",
    address: "No. 4, Bank of Ceylon Mawatha, Colombo 01, Sri Lanka",
    telephone: "+94112332853",
    email: "col1branch@boc.lk",
    fax: "+94112447737",
    bankCEOName: "K.E.D. Sumanasiri",
  },
  {
    id: 2,
    branchCode: "SAMP-COL4",
    branchName: "Sampath Bank - Bambalapitiya",
    bankCode: "SAMP002",
    bankCEO: "Nanda Fernando",
    city: "Colombo 04",
    district: "Colombo",
    address: "285, Galle Road, Bambalapitiya, Colombo 04, Sri Lanka",
    telephone: "+94112505741",
    email: "bambalapitiya@sampathbank.lk",
    fax: "+94112586361",
    bankCEOName: "Nanda Fernando",
  },
  {
    id: 3,
    branchCode: "COM-KAN1",
    branchName: "Commercial Bank - Kandy",
    bankCode: "COM003",
    bankCEO: "S. Renganathan",
    city: "Kandy",
    district: "Kandy",
    address: "120, Kotugodella Street, Kandy, Sri Lanka",
    telephone: "+94812234356",
    email: "kandy@combank.lk",
    fax: "+94812234357",
    bankCEOName: "S. Renganathan",
  },
  {
    id: 4,
    branchCode: "HNB-GAL1",
    branchName: "Hatton National Bank - Galle Fort",
    bankCode: "HNB004",
    bankCEO: "Jonathan Alles",
    city: "Galle",
    district: "Galle",
    address: "25A, Church Street, Fort, Galle, Sri Lanka",
    telephone: "+94912234522",
    email: "gallefort@hnb.lk",
    fax: "+94912234523",
    bankCEOName: "Jonathan Alles",
  },
  {
    id: 5,
    branchCode: "NSB-NEG1",
    branchName: "National Savings Bank - Negombo",
    bankCode: "NSB005",
    bankCEO: "Ajith Peiris",
    city: "Negombo",
    district: "Gampaha",
    address: "178, Main Street, Negombo, Sri Lanka",
    telephone: "+94312224533",
    email: "negombo@nsb.lk",
    fax: "+94312224534",
    bankCEOName: "Ajith Peiris",
  },
  {
    id: 6,
    branchCode: "PB-ANR1",
    branchName: "People's Bank - Anuradhapura",
    bankCode: "PB006",
    bankCEO: "Ranjith Kodituwakku",
    city: "Anuradhapura",
    district: "Anuradhapura",
    address: "65, Maithripala Senanayake Mawatha, Anuradhapura, Sri Lanka",
    telephone: "+94252222678",
    email: "anuradhapura@peoplesbank.lk",
    fax: "+94252222679",
    bankCEOName: "Ranjith Kodituwakku",
  },
  {
    id: 7,
    branchCode: "SEYB-MAT1",
    branchName: "Seylan Bank - Matara",
    bankCode: "SEYB007",
    bankCEO: "Kapila Ariyaratne",
    city: "Matara",
    district: "Matara",
    address: "32, Anagarika Dharmapala Mawatha, Matara, Sri Lanka",
    telephone: "+94412222890",
    email: "matara@seylan.lk",
    fax: "+94412222891",
    bankCEOName: "Kapila Ariyaratne",
  },
  {
    id: 8,
    branchCode: "NDB-COL7",
    branchName: "National Development Bank - Cinnamon Gardens",
    bankCode: "NDB008",
    bankCEO: "Dimantha Seneviratne",
    city: "Colombo 07",
    district: "Colombo",
    address: "42, Ward Place, Colombo 07, Sri Lanka",
    telephone: "+94112667890",
    email: "cinnamongardens@ndbbank.com",
    fax: "+94112667891",
    bankCEOName: "Dimantha Seneviratne",
  },
  {
    id: 9,
    branchCode: "DFCC-KUR1",
    branchName: "DFCC Bank - Kurunegala",
    bankCode: "DFCC009",
    bankCEO: "Lakshman Silva",
    city: "Kurunegala",
    district: "Kurunegala",
    address: "15, Colombo Road, Kurunegala, Sri Lanka",
    telephone: "+94372223456",
    email: "kurunegala@dfccbank.com",
    fax: "+94372223457",
    bankCEOName: "Lakshman Silva",
  },
  {
    id: 10,
    branchCode: "PABC-JAF1",
    branchName: "Pan Asia Banking Corporation - Jaffna",
    bankCode: "PABC010",
    bankCEO: "Nimal Tillekeratne",
    city: "Jaffna",
    district: "Jaffna",
    address: "88, Main Street, Jaffna, Sri Lanka",
    telephone: "+94212228975",
    email: "jaffna@pabcbank.com",
    fax: "+94212228976",
    bankCEOName: "Nimal Tillekeratne",
  },
];

const mockLocations = [
  {
    id: 1,
    locationCode: "LOC-COL-001",
    type: "Main",
    description: "Colombo Main Warehouse",
  },
  {
    id: 2,
    locationCode: "LOC-KAN-001",
    type: "Rep",
    description: "Kandy Regional Distribution Center",
  },
  {
    id: 3,
    locationCode: "LOC-GAL-001",
    type: "Rep",
    description: "Galle Service Center",
  },
  {
    id: 4,
    locationCode: "LOC-JAF-001",
    type: "Rep",
    description: "Jaffna Parts Depot",
  },
  {
    id: 5,
    locationCode: "LOC-ANR-001",
    type: "Rep",
    description: "Anuradhapura Regional Store",
  },
  {
    id: 6,
    locationCode: "LOC-COL-002",
    type: "Other",
    description: "Colombo Display Room",
  },
  {
    id: 7,
    locationCode: "LOC-MAT-001",
    type: "Rep",
    description: "Matara Service Center",
  },
  {
    id: 8,
    locationCode: "LOC-KUR-001",
    type: "Rep",
    description: "Kurunegala Parts Outlet",
  },
  {
    id: 9,
    locationCode: "LOC-NEG-001",
    type: "Rep",
    description: "Negombo Service Point",
  },
  {
    id: 10,
    locationCode: "LOC-COL-003",
    type: "Other",
    description: "Colombo Transit Storage",
  },
];

const mockAreas = [
  {
    id: 1,
    areaCode: "AREA001",
    areaName: "Colombo Central",
    cityName: "Colombo",
    routeCode: "ROUTE001",
  },
  {
    id: 2,
    areaCode: "AREA002",
    areaName: "Kandy City",
    cityName: "Kandy",
    routeCode: "ROUTE021",
  },
  {
    id: 3,
    areaCode: "AREA003",
    areaName: "Galle Fort",
    cityName: "Galle",
    routeCode: "ROUTE042",
  },
  {
    id: 4,
    areaCode: "AREA004",
    areaName: "Jaffna Peninsula",
    cityName: "Jaffna",
    routeCode: "ROUTE078",
  },
  {
    id: 5,
    areaCode: "AREA005",
    areaName: "Negombo Beach",
    cityName: "Negombo",
    routeCode: "ROUTE033",
  },
  {
    id: 6,
    areaCode: "AREA006",
    areaName: "Matara Coast",
    cityName: "Matara",
    routeCode: "ROUTE055",
  },
  {
    id: 7,
    areaCode: "AREA007",
    areaName: "Anuradhapura Ancient City",
    cityName: "Anuradhapura",
    routeCode: "ROUTE061",
  },
  {
    id: 8,
    areaCode: "AREA008",
    areaName: "Kurunegala Central",
    cityName: "Kurunegala",
    routeCode: "ROUTE047",
  },
  {
    id: 9,
    areaCode: "AREA009",
    areaName: "Ratnapura Gem District",
    cityName: "Ratnapura",
    routeCode: "ROUTE089",
  },
  {
    id: 10,
    areaCode: "AREA010",
    areaName: "Batticaloa Eastern",
    cityName: "Batticaloa",
    routeCode: "ROUTE102",
  },
];

const mockRoutes = [
  {
    id: 1,
    routeCode: "ROUTE001",
    description: "Colombo City Center to Suburbs",
  },
  {
    id: 2,
    routeCode: "ROUTE021",
    description: "Kandy Central Distribution Loop",
  },
  {
    id: 3,
    routeCode: "ROUTE042",
    description: "Galle Coastal Highway Route",
  },
  {
    id: 4,
    routeCode: "ROUTE078",
    description: "Jaffna Peninsula Delivery Network",
  },
  {
    id: 5,
    routeCode: "ROUTE033",
    description: "Negombo-Colombo Airport Corridor",
  },
  {
    id: 6,
    routeCode: "ROUTE055",
    description: "Matara-Hambantota Southern Route",
  },
  {
    id: 7,
    routeCode: "ROUTE061",
    description: "Anuradhapura Ancient City Circuit",
  },
  {
    id: 8,
    routeCode: "ROUTE047",
    description: "Kurunegala-Dambulla Central Link",
  },
  {
    id: 9,
    routeCode: "ROUTE089",
    description: "Ratnapura-Embilipitiya Gem Route",
  },
  {
    id: 10,
    routeCode: "ROUTE102",
    description: "Batticaloa Eastern Coastal Highway",
  },
];

const mockTransportAgents = [
  {
    id: 1,
    agentCode: "AGT001",
    agentName: "Express Logistics Lanka",
    contactName: "Dinesh Fernando",
    address: "45 Freight Avenue, Colombo 15, Sri Lanka",
  },
  {
    id: 2,
    agentCode: "AGT002",
    agentName: "Swift Delivery Services",
    contactName: "Priyanka Jayawardena",
    address: "78A Transport Road, Negombo, Sri Lanka",
  },
  {
    id: 3,
    agentCode: "AGT003",
    agentName: "Central Cargo Movers",
    contactName: "Anura Dissanayake",
    address: "123 Peradeniya Road, Kandy, Sri Lanka",
  },
  {
    id: 4,
    agentCode: "AGT004",
    agentName: "Southern Route Carriers",
    contactName: "Lasith Malinga",
    address: "35 Harbor Road, Galle, Sri Lanka",
  },
  {
    id: 5,
    agentCode: "AGT005",
    agentName: "Northern Star Transport",
    contactName: "Vijay Kumaran",
    address: "56 Main Street, Jaffna, Sri Lanka",
  },
  {
    id: 6,
    agentCode: "AGT006",
    agentName: "Rapid Delivery Solutions",
    contactName: "Chaminda Vaas",
    address: "87 Industrial Zone, Biyagama, Sri Lanka",
  },
  {
    id: 7,
    agentCode: "AGT007",
    agentName: "Island-wide Logistics",
    contactName: "Roshan Mahanama",
    address: "102 Trade Center Road, Colombo 01, Sri Lanka",
  },
  {
    id: 8,
    agentCode: "AGT008",
    agentName: "Eastern Freight Services",
    contactName: "Mohamed Faizal",
    address: "29 Coastal Road, Batticaloa, Sri Lanka",
  },
  {
    id: 9,
    agentCode: "AGT009",
    agentName: "Highland Transporters",
    contactName: "Nuwani Perera",
    address: "44 Hill Street, Nuwara Eliya, Sri Lanka",
  },
  {
    id: 10,
    agentCode: "AGT010",
    agentName: "Prime Carriers Ltd",
    contactName: "Kumar Sangakkara",
    address: "77 Commercial Avenue, Colombo 03, Sri Lanka",
  },
];

const mockUtilities = [
  {
    id: 1,
    expenseReferenceNumber: "UTIL-ELEC-2025-001",
    expenseCode: "ELEC-COL",
    description: "Electricity Bill - Colombo Main Office",
    period: "2025-01-01 to 2025-01-31",
    amount: 145000,
    outstanding: 145000,
  },
  {
    id: 2,
    expenseReferenceNumber: "UTIL-WATER-2025-001",
    expenseCode: "WATER-COL",
    description: "Water Bill - Colombo Main Office",
    period: "2025-01-01 to 2025-01-31",
    amount: 35000,
    outstanding: 35000,
  },
  {
    id: 3,
    expenseReferenceNumber: "UTIL-RENT-2025-Q1",
    expenseCode: "RENT-KDY",
    description: "Office Rent - Kandy Branch",
    period: "2025-01-01 to 2025-03-31",
    amount: 450000,
    outstanding: 450000,
  },
  {
    id: 4,
    expenseReferenceNumber: "UTIL-INTERNET-2025-001",
    expenseCode: "INET-ALL",
    description: "Internet Services - All Locations",
    period: "2025-01-01 to 2025-01-31",
    amount: 78000,
    outstanding: 0,
  },
  {
    id: 5,
    expenseReferenceNumber: "UTIL-PHONE-2025-001",
    expenseCode: "PHONE-ALL",
    description: "Telephone Services - All Locations",
    period: "2025-01-01 to 2025-01-31",
    amount: 42500,
    outstanding: 12500,
  },
  {
    id: 6,
    expenseReferenceNumber: "UTIL-ELEC-2025-002",
    expenseCode: "ELEC-GAL",
    description: "Electricity Bill - Galle Branch",
    period: "2025-01-01 to 2025-01-31",
    amount: 68000,
    outstanding: 68000,
  },
  {
    id: 7,
    expenseReferenceNumber: "UTIL-MAINT-2025-Q1",
    expenseCode: "MAINT-WARE",
    description: "Warehouse Maintenance",
    period: "2025-01-01 to 2025-03-31",
    amount: 125000,
    outstanding: 125000,
  },
  {
    id: 8,
    expenseReferenceNumber: "UTIL-SEC-2025-001",
    expenseCode: "SEC-ALL",
    description: "Security Services - All Locations",
    period: "2025-01-01 to 2025-01-31",
    amount: 95000,
    outstanding: 0,
  },
  {
    id: 9,
    expenseReferenceNumber: "UTIL-GEN-2025-001",
    expenseCode: "GEN-FUEL",
    description: "Generator Fuel - Colombo Main Office",
    period: "2025-01-01 to 2025-01-31",
    amount: 56000,
    outstanding: 56000,
  },
  {
    id: 10,
    expenseReferenceNumber: "UTIL-CLEAN-2025-001",
    expenseCode: "CLEAN-ALL",
    description: "Cleaning Services - All Locations",
    period: "2025-01-01 to 2025-01-31",
    amount: 48000,
    outstanding: 15000,
  },
];

const mockHSCodes = [
  {
    id: 1,
    item: "Engine Parts",
    itemDescription: "Spark plugs for internal combustion engines",
    hsCodeNumber: "8511.10.00",
    dutyRate: 15,
    palRate: 10,
    ssclRate: 2.5,
    eicKGRate: 1.2,
    vatPercentage: 15,
    remarks: "Used in both petrol and diesel engines, common import item",
  },
  {
    id: 2,
    item: "Brake System",
    itemDescription: "Mounted brake linings for motor vehicles",
    hsCodeNumber: "8708.30.10",
    dutyRate: 25,
    palRate: 7.5,
    ssclRate: 3.0,
    eicKGRate: 0.8,
    vatPercentage: 15,
    remarks: "High demand for Japanese vehicle models",
  },
  {
    id: 3,
    item: "Transmission Parts",
    itemDescription: "Gear boxes for motor vehicles",
    hsCodeNumber: "8708.40.00",
    dutyRate: 30,
    palRate: 12,
    ssclRate: 4.0,
    eicKGRate: 2.5,
    vatPercentage: 15,
    remarks: "Automatic transmission components subject to special handling",
  },
  {
    id: 4,
    item: "Suspension System",
    itemDescription: "Shock absorbers for motor vehicles",
    hsCodeNumber: "8708.80.00",
    dutyRate: 20,
    palRate: 8,
    ssclRate: 2.0,
    eicKGRate: 1.0,
    vatPercentage: 15,
    remarks: "Heavy-duty variants for commercial vehicles available",
  },
  {
    id: 5,
    item: "Electrical Components",
    itemDescription: "Starter motors and generators for vehicles",
    hsCodeNumber: "8511.40.00",
    dutyRate: 18,
    palRate: 9,
    ssclRate: 3.5,
    eicKGRate: 0.7,
    vatPercentage: 15,
    remarks: "Compatible with 12V and 24V systems",
  },
  {
    id: 6,
    item: "Body Parts",
    itemDescription: "Bumpers and parts for motor vehicles",
    hsCodeNumber: "8708.10.00",
    dutyRate: 35,
    palRate: 15,
    ssclRate: 5.0,
    eicKGRate: 3.0,
    vatPercentage: 15,
    remarks: "Size and weight affect shipping costs significantly",
  },
  {
    id: 7,
    item: "Cooling System",
    itemDescription: "Radiators for motor vehicles",
    hsCodeNumber: "8708.91.00",
    dutyRate: 22,
    palRate: 8.5,
    ssclRate: 2.8,
    eicKGRate: 1.5,
    vatPercentage: 15,
    remarks: "Aluminum variants preferred for newer models",
  },
  {
    id: 8,
    item: "Exhaust System",
    itemDescription: "Silencers and exhaust pipes",
    hsCodeNumber: "8708.92.00",
    dutyRate: 28,
    palRate: 11,
    ssclRate: 3.2,
    eicKGRate: 2.0,
    vatPercentage: 15,
    remarks: "Environmental standards compliance required",
  },
  {
    id: 9,
    item: "Filters",
    itemDescription: "Oil and air filters for internal combustion engines",
    hsCodeNumber: "8421.23.00",
    dutyRate: 12,
    palRate: 6,
    ssclRate: 1.8,
    eicKGRate: 0.5,
    vatPercentage: 15,
    remarks: "High turnover inventory item, regular imports",
  },
  {
    id: 10,
    item: "Lighting Equipment",
    itemDescription: "Headlamps and signal lights for vehicles",
    hsCodeNumber: "8512.20.00",
    dutyRate: 25,
    palRate: 10,
    ssclRate: 3.5,
    eicKGRate: 1.0,
    vatPercentage: 15,
    remarks: "LED variants becoming more popular than halogen",
  },
];

const mockCategories = [
  {
    id: 1,
    categoryCode: "CAT001",
    categoryDescription: "Engine Components",
  },
  {
    id: 2,
    categoryCode: "CAT002",
    categoryDescription: "Transmission Parts",
  },
  {
    id: 3,
    categoryCode: "CAT003",
    categoryDescription: "Brake Systems",
  },
  {
    id: 4,
    categoryCode: "CAT004",
    categoryDescription: "Electrical Systems",
  },
  {
    id: 5,
    categoryCode: "CAT005",
    categoryDescription: "Suspension & Steering",
  },
  {
    id: 6,
    categoryCode: "CAT006",
    categoryDescription: "Body Parts & Accessories",
  },
  {
    id: 7,
    categoryCode: "CAT007",
    categoryDescription: "Lubricants & Fluids",
  },
  {
    id: 8,
    categoryCode: "CAT008",
    categoryDescription: "Filters & Air Systems",
  },
  {
    id: 9,
    categoryCode: "CAT009",
    categoryDescription: "Cooling Systems",
  },
  {
    id: 10,
    categoryCode: "CAT010",
    categoryDescription: "Lighting & Signaling",
  },
];

const mockClassifications = [
  {
    id: 1,
    classificationCode: "CLS001",
    classificationDescription: "Japanese Vehicles",
  },
  {
    id: 2,
    classificationCode: "CLS002",
    classificationDescription: "European Vehicles",
  },
  {
    id: 3,
    classificationCode: "CLS003",
    classificationDescription: "Commercial Vehicles",
  },
  {
    id: 4,
    classificationCode: "CLS004",
    classificationDescription: "Passenger Cars",
  },
  {
    id: 5,
    classificationCode: "CLS005",
    classificationDescription: "SUVs and Crossovers",
  },
  {
    id: 6,
    classificationCode: "CLS006",
    classificationDescription: "Motorcycle Parts",
  },
  {
    id: 7,
    classificationCode: "CLS007",
    classificationDescription: "High Performance Components",
  },
  {
    id: 8,
    classificationCode: "CLS008",
    classificationDescription: "Genuine OEM Parts",
  },
  {
    id: 9,
    classificationCode: "CLS009",
    classificationDescription: "Aftermarket Accessories",
  },
  {
    id: 10,
    classificationCode: "CLS010",
    classificationDescription: "Heavy Machinery Components",
  },
];

const mockReasonRemarks = [
  {
    id: 1,
    reasonRemarkCode: "RM001",
    description: "Insufficient Funds",
    category: "Q",
    type: "Reason",
  },
  {
    id: 2,
    reasonRemarkCode: "RM002",
    description: "Account Closed",
    category: "Q",
    type: "Reason",
  },
  {
    id: 3,
    reasonRemarkCode: "RM003",
    description: "Payment Pending Approval",
    category: "P",
    type: "Remark",
  },
  {
    id: 4,
    reasonRemarkCode: "RM004",
    description: "Damaged in Transit",
    category: "I",
    type: "Reason",
  },
  {
    id: 5,
    reasonRemarkCode: "RM005",
    description: "Wrong Item Shipped",
    category: "I",
    type: "Reason",
  },
  {
    id: 6,
    reasonRemarkCode: "RM006",
    description: "Awaiting Signature Verification",
    category: "Q",
    type: "Remark",
  },
  {
    id: 7,
    reasonRemarkCode: "RM007",
    description: "Credit Limit Exceeded",
    category: "P",
    type: "Reason",
  },
  {
    id: 8,
    reasonRemarkCode: "RM008",
    description: "Item No Longer Needed",
    category: "I",
    type: "Reason",
  },
  {
    id: 9,
    reasonRemarkCode: "RM009",
    description: "Awaiting Additional Documentation",
    category: "P",
    type: "Remark",
  },
  {
    id: 10,
    reasonRemarkCode: "RM010",
    description: "Payment Stopped by Customer",
    category: "Q",
    type: "Reason",
  },
];

const mockSalesReps = [
  {
    id: 1,
    repCode: "REP001",
    repName: "Sunil Perera",
    acCode: "ACC5001",
    acName: "Sales Account Colombo",
    email: "sunil.perera@zerendib.lk",
    mobilePhone: "+94771234567",
    monthlyTarget: 3500000,
    // Route 1 data
    route1Code: "ROUTE001",
    route1Name: "Colombo City Center to Suburbs",
    route1Slab1: 1,
    route1Slab1Target: 1000000,
    route1Slab1IncentiveRate: 2.5,
    route1Slab1IncentiveAmount: 25000,
    route1Slab2: 2,
    route1Slab2Target: 2000000,
    route1Slab2IncentiveRate: 3.5,
    route1Slab2IncentiveAmount: 70000,
    route1Slab3: 3,
    route1Slab3Target: 3000000,
    route1Slab3IncentiveRate: 5.0,
    route1Slab3IncentiveAmount: 150000,
    // Route 2 data
    route2Code: "ROUTE021",
    route2Name: "Kandy Central Distribution Loop",
    route2Slab1: 1,
    route2Slab1Target: 850000,
    route2Slab1IncentiveRate: 2.0,
    route2Slab1IncentiveAmount: 17000,
    route2Slab2: 2,
    route2Slab2Target: 1750000,
    route2Slab2IncentiveRate: 3.0,
    route2Slab2IncentiveAmount: 52500,
    route2Slab3: 3,
    route2Slab3Target: 2500000,
    route2Slab3IncentiveRate: 4.5,
    route2Slab3IncentiveAmount: 112500,
    // Route 3 data
    route3Code: "ROUTE042",
    route3Name: "Galle Coastal Highway Route",
    route3Slab1: 1,
    route3Slab1Target: 750000,
    route3Slab1IncentiveRate: 2.2,
    route3Slab1IncentiveAmount: 16500,
    route3Slab2: 2,
    route3Slab2Target: 1500000,
    route3Slab2IncentiveRate: 3.2,
    route3Slab2IncentiveAmount: 48000,
    route3Slab3: 3,
    route3Slab3Target: 2200000,
    route3Slab3IncentiveRate: 4.0,
    route3Slab3IncentiveAmount: 88000,
  },
  {
    id: 2,
    repCode: "REP002",
    repName: "Priyanka Silva",
    acCode: "ACC5002",
    acName: "Sales Account Central",
    email: "priyanka.silva@zerendib.lk",
    mobilePhone: "+94772345678",
    monthlyTarget: 3000000,
    // Route 1 data
    route1Code: "ROUTE033",
    route1Name: "Negombo-Colombo Airport Corridor",
    route1Slab1: 1,
    route1Slab1Target: 900000,
    route1Slab1IncentiveRate: 2.0,
    route1Slab1IncentiveAmount: 18000,
    route1Slab2: 2,
    route1Slab2Target: 1800000,
    route1Slab2IncentiveRate: 3.0,
    route1Slab2IncentiveAmount: 54000,
    route1Slab3: 3,
    route1Slab3Target: 2700000,
    route1Slab3IncentiveRate: 4.5,
    route1Slab3IncentiveAmount: 121500,
    // Route 2 data
    route2Code: "ROUTE047",
    route2Name: "Kurunegala-Dambulla Central Link",
    route2Slab1: 1,
    route2Slab1Target: 800000,
    route2Slab1IncentiveRate: 1.8,
    route2Slab1IncentiveAmount: 14400,
    route2Slab2: 2,
    route2Slab2Target: 1600000,
    route2Slab2IncentiveRate: 2.8,
    route2Slab2IncentiveAmount: 44800,
    route2Slab3: 3,
    route2Slab3Target: 2400000,
    route2Slab3IncentiveRate: 4.2,
    route2Slab3IncentiveAmount: 100800,
    // Route 3 data
    route3Code: "ROUTE055",
    route3Name: "Matara-Hambantota Southern Route",
    route3Slab1: 1,
    route3Slab1Target: 700000,
    route3Slab1IncentiveRate: 2.0,
    route3Slab1IncentiveAmount: 14000,
    route3Slab2: 2,
    route3Slab2Target: 1400000,
    route3Slab2IncentiveRate: 3.0,
    route3Slab2IncentiveAmount: 42000,
    route3Slab3: 3,
    route3Slab3Target: 2100000,
    route3Slab3IncentiveRate: 4.0,
    route3Slab3IncentiveAmount: 84000,
  },
  {
    id: 3,
    repCode: "REP003",
    repName: "Mohamed Farook",
    acCode: "ACC5003",
    acName: "Sales Account Eastern",
    email: "mohamed.farook@zerendib.lk",
    mobilePhone: "+94773456789",
    monthlyTarget: 2800000,
    // Route 1 data
    route1Code: "ROUTE061",
    route1Name: "Anuradhapura Ancient City Circuit",
    route1Slab1: 1,
    route1Slab1Target: 850000,
    route1Slab1IncentiveRate: 2.2,
    route1Slab1IncentiveAmount: 18700,
    route1Slab2: 2,
    route1Slab2Target: 1700000,
    route1Slab2IncentiveRate: 3.2,
    route1Slab2IncentiveAmount: 54400,
    route1Slab3: 3,
    route1Slab3Target: 2550000,
    route1Slab3IncentiveRate: 4.5,
    route1Slab3IncentiveAmount: 114750,
    // Route 2 data
    route2Code: "ROUTE078",
    route2Name: "Jaffna Peninsula Delivery Network",
    route2Slab1: 1,
    route2Slab1Target: 750000,
    route2Slab1IncentiveRate: 2.0,
    route2Slab1IncentiveAmount: 15000,
    route2Slab2: 2,
    route2Slab2Target: 1500000,
    route2Slab2IncentiveRate: 3.0,
    route2Slab2IncentiveAmount: 45000,
    route2Slab3: 3,
    route2Slab3Target: 2250000,
    route2Slab3IncentiveRate: 4.2,
    route2Slab3IncentiveAmount: 94500,
    // Route 3 data
    route3Code: "ROUTE102",
    route3Name: "Batticaloa Eastern Coastal Highway",
    route3Slab1: 1,
    route3Slab1Target: 650000,
    route3Slab1IncentiveRate: 1.8,
    route3Slab1IncentiveAmount: 11700,
    route3Slab2: 2,
    route3Slab2Target: 1300000,
    route3Slab2IncentiveRate: 2.8,
    route3Slab2IncentiveAmount: 36400,
    route3Slab3: 3,
    route3Slab3Target: 1950000,
    route3Slab3IncentiveRate: 3.8,
    route3Slab3IncentiveAmount: 74100,
  },
  {
    id: 4,
    repCode: "REP004",
    repName: "Kumari Dissanayake",
    acCode: "ACC5004",
    acName: "Sales Account Northern",
    email: "kumari.dissanayake@zerendib.lk",
    mobilePhone: "+94774567890",
    monthlyTarget: 2600000,
    // Route 1 data
    route1Code: "ROUTE089",
    route1Name: "Ratnapura Gem District Circuit",
    route1Slab1: 1,
    route1Slab1Target: 800000,
    route1Slab1IncentiveRate: 2.0,
    route1Slab1IncentiveAmount: 16000,
    route1Slab2: 2,
    route1Slab2Target: 1600000,
    route1Slab2IncentiveRate: 3.0,
    route1Slab2IncentiveAmount: 48000,
    route1Slab3: 3,
    route1Slab3Target: 2400000,
    route1Slab3IncentiveRate: 4.0,
    route1Slab3IncentiveAmount: 96000,
    // Route 2 data
    route2Code: "ROUTE033",
    route2Name: "Nuwara Eliya Highland Route",
    route2Slab1: 1,
    route2Slab1Target: 750000,
    route2Slab1IncentiveRate: 1.8,
    route2Slab1IncentiveAmount: 13500,
    route2Slab2: 2,
    route2Slab2Target: 1500000,
    route2Slab2IncentiveRate: 2.8,
    route2Slab2IncentiveAmount: 42000,
    route2Slab3: 3,
    route2Slab3Target: 2250000,
    route2Slab3IncentiveRate: 4.0,
    route2Slab3IncentiveAmount: 90000,
    // Route 3 data
    route3Code: "ROUTE078",
    route3Name: "Trincomalee Coastal Delivery Circuit",
    route3Slab1: 1,
    route3Slab1Target: 600000,
    route3Slab1IncentiveRate: 1.5,
    route3Slab1IncentiveAmount: 9000,
    route3Slab2: 2,
    route3Slab2Target: 1200000,
    route3Slab2IncentiveRate: 2.5,
    route3Slab2IncentiveAmount: 30000,
    route3Slab3: 3,
    route3Slab3Target: 1800000,
    route3Slab3IncentiveRate: 3.5,
    route3Slab3IncentiveAmount: 63000,
  },
  {
    id: 5,
    repCode: "REP005",
    repName: "Ajith Bandara",
    acCode: "ACC5005",
    acName: "Sales Account Southern",
    email: "ajith.bandara@zerendib.lk",
    mobilePhone: "+94775678901",
    monthlyTarget: 3200000,
    // Route 1 data
    route1Code: "ROUTE055",
    route1Name: "Matara-Hambantota Southern Route",
    route1Slab1: 1,
    route1Slab1Target: 950000,
    route1Slab1IncentiveRate: 2.3,
    route1Slab1IncentiveAmount: 21850,
    route1Slab2: 2,
    route1Slab2Target: 1900000,
    route1Slab2IncentiveRate: 3.3,
    route1Slab2IncentiveAmount: 62700,
    route1Slab3: 3,
    route1Slab3Target: 2850000,
    route1Slab3IncentiveRate: 4.8,
    route1Slab3IncentiveAmount: 136800,
    // Route 2 data
    route2Code: "ROUTE042",
    route2Name: "Galle Coastal Highway Route",
    route2Slab1: 1,
    route2Slab1Target: 880000,
    route2Slab1IncentiveRate: 2.1,
    route2Slab1IncentiveAmount: 18480,
    route2Slab2: 2,
    route2Slab2Target: 1760000,
    route2Slab2IncentiveRate: 3.1,
    route2Slab2IncentiveAmount: 54560,
    route2Slab3: 3,
    route2Slab3Target: 2640000,
    route2Slab3IncentiveRate: 4.6,
    route2Slab3IncentiveAmount: 121440,
    // Route 3 data
    route3Code: "ROUTE001",
    route3Name: "Colombo South Distribution",
    route3Slab1: 1,
    route3Slab1Target: 700000,
    route3Slab1IncentiveRate: 1.9,
    route3Slab1IncentiveAmount: 13300,
    route3Slab2: 2,
    route3Slab2Target: 1400000,
    route3Slab2IncentiveRate: 2.9,
    route3Slab2IncentiveAmount: 40600,
    route3Slab3: 3,
    route3Slab3Target: 2100000,
    route3Slab3IncentiveRate: 4.4,
    route3Slab3IncentiveAmount: 92400,
  },
];

const mockShopReps = [
  {
    id: 1,
    repCode: "REP001",
    shopRepCode: "SHOP001",
    shopRepName: "Kamal Jayasinghe",
  },
  {
    id: 2,
    repCode: "REP001",
    shopRepCode: "SHOP002",
    shopRepName: "Samantha Perera",
  },
  {
    id: 3,
    repCode: "REP002",
    shopRepCode: "SHOP003",
    shopRepName: "Nimal Fernando",
  },
  {
    id: 4,
    repCode: "REP002",
    shopRepCode: "SHOP004",
    shopRepName: "Ruwan Dissanayake",
  },
  {
    id: 5,
    repCode: "REP003",
    shopRepCode: "SHOP005",
    shopRepName: "Amara Ratnayake",
  },
  {
    id: 6,
    repCode: "REP003",
    shopRepCode: "SHOP006",
    shopRepName: "Fathima Nizam",
  },
  {
    id: 7,
    repCode: "REP004",
    shopRepCode: "SHOP007",
    shopRepName: "Chandana Gunawardena",
  },
  {
    id: 8,
    repCode: "REP004",
    shopRepCode: "SHOP008",
    shopRepName: "Deepika Mendis",
  },
  {
    id: 9,
    repCode: "REP005",
    shopRepCode: "SHOP009",
    shopRepName: "Hasith Kulatunga",
  },
  {
    id: 10,
    repCode: "REP005",
    shopRepCode: "SHOP010",
    shopRepName: "Lakshmi Weerasekara",
  },
];

const mockItemWholeSaleSlabs = [
  {
    id: 1,
    itemCode: "ITM001",
    itemDescription: "Heavy Duty Engine Oil (5L)",
    compareQuantity: 100,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 10,
    slab1Price: 5200,
    slab1Discount: 5,
    slab2Number: 2,
    slab2From: 11,
    slab2To: 25,
    slab2Price: 5000,
    slab2Discount: 7.5,
    slab3Number: 3,
    slab3From: 26,
    slab3To: 50,
    slab3Price: 4850,
    slab3Discount: 10,
    slab4Number: 4,
    slab4From: 51,
    slab4To: 100,
    slab4Price: 4700,
    slab4Discount: 12.5,
  },
  {
    id: 2,
    itemCode: "ITM002",
    itemDescription: "Premium Brake Pads (Set of 4)",
    compareQuantity: 50,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 5,
    slab1Price: 7500,
    slab1Discount: 3,
    slab2Number: 2,
    slab2From: 6,
    slab2To: 15,
    slab2Price: 7250,
    slab2Discount: 5,
    slab3Number: 3,
    slab3From: 16,
    slab3To: 30,
    slab3Price: 7000,
    slab3Discount: 8,
    slab4Number: 4,
    slab4From: 31,
    slab4To: 50,
    slab4Price: 6750,
    slab4Discount: 10,
  },
  {
    id: 3,
    itemCode: "ITM003",
    itemDescription: "Air Filter Element",
    compareQuantity: 200,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 20,
    slab1Price: 1200,
    slab1Discount: 2,
    slab2Number: 2,
    slab2From: 21,
    slab2To: 50,
    slab2Price: 1150,
    slab2Discount: 4,
    slab3Number: 3,
    slab3From: 51,
    slab3To: 100,
    slab3Price: 1100,
    slab3Discount: 7,
    slab4Number: 4,
    slab4From: 101,
    slab4To: 200,
    slab4Price: 1050,
    slab4Discount: 12,
  },
  {
    id: 4,
    itemCode: "ITM004",
    itemDescription: "Fuel Injection Cleaner (250ml)",
    compareQuantity: 150,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 15,
    slab1Price: 850,
    slab1Discount: 2.5,
    slab2Number: 2,
    slab2From: 16,
    slab2To: 40,
    slab2Price: 825,
    slab2Discount: 5,
    slab3Number: 3,
    slab3From: 41,
    slab3To: 80,
    slab3Price: 800,
    slab3Discount: 7.5,
    slab4Number: 4,
    slab4From: 81,
    slab4To: 150,
    slab4Price: 775,
    slab4Discount: 10,
  },
  {
    id: 5,
    itemCode: "ITM005",
    itemDescription: "Spark Plugs - Iridium (Pack of 4)",
    compareQuantity: 80,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 8,
    slab1Price: 3200,
    slab1Discount: 3,
    slab2Number: 2,
    slab2From: 9,
    slab2To: 20,
    slab2Price: 3100,
    slab2Discount: 6,
    slab3Number: 3,
    slab3From: 21,
    slab3To: 40,
    slab3Price: 3000,
    slab3Discount: 8,
    slab4Number: 4,
    slab4From: 41,
    slab4To: 80,
    slab4Price: 2900,
    slab4Discount: 12,
  },
  {
    id: 6,
    itemCode: "ITM006",
    itemDescription: "Transmission Fluid (1L)",
    compareQuantity: 120,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 12,
    slab1Price: 2800,
    slab1Discount: 4,
    slab2Number: 2,
    slab2From: 13,
    slab2To: 30,
    slab2Price: 2700,
    slab2Discount: 6,
    slab3Number: 3,
    slab3From: 31,
    slab3To: 60,
    slab3Price: 2600,
    slab3Discount: 9,
    slab4Number: 4,
    slab4From: 61,
    slab4To: 120,
    slab4Price: 2500,
    slab4Discount: 15,
  },
  {
    id: 7,
    itemCode: "ITM007",
    itemDescription: "Radiator Coolant (2L)",
    compareQuantity: 100,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 10,
    slab1Price: 1800,
    slab1Discount: 3,
    slab2Number: 2,
    slab2From: 11,
    slab2To: 25,
    slab2Price: 1750,
    slab2Discount: 5.5,
    slab3Number: 3,
    slab3From: 26,
    slab3To: 50,
    slab3Price: 1700,
    slab3Discount: 8.5,
    slab4Number: 4,
    slab4From: 51,
    slab4To: 100,
    slab4Price: 1650,
    slab4Discount: 12,
  },
  {
    id: 8,
    itemCode: "ITM008",
    itemDescription: "Wiper Blades - Premium (Pair)",
    compareQuantity: 90,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 9,
    slab1Price: 2400,
    slab1Discount: 2,
    slab2Number: 2,
    slab2From: 10,
    slab2To: 22,
    slab2Price: 2350,
    slab2Discount: 4,
    slab3Number: 3,
    slab3From: 23,
    slab3To: 45,
    slab3Price: 2300,
    slab3Discount: 7,
    slab4Number: 4,
    slab4From: 46,
    slab4To: 90,
    slab4Price: 2250,
    slab4Discount: 10,
  },
  {
    id: 9,
    itemCode: "ITM009",
    itemDescription: "Brake Fluid DOT4 (500ml)",
    compareQuantity: 75,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 7,
    slab1Price: 1500,
    slab1Discount: 2.5,
    slab2Number: 2,
    slab2From: 8,
    slab2To: 18,
    slab2Price: 1450,
    slab2Discount: 5,
    slab3Number: 3,
    slab3From: 19,
    slab3To: 37,
    slab3Price: 1400,
    slab3Discount: 7.5,
    slab4Number: 4,
    slab4From: 38,
    slab4To: 75,
    slab4Price: 1350,
    slab4Discount: 12,
  },
  {
    id: 10,
    itemCode: "ITM010",
    itemDescription: "Timing Belt Kit",
    compareQuantity: 30,
    slab1Number: 1,
    slab1From: 1,
    slab1To: 3,
    slab1Price: 12000,
    slab1Discount: 5,
    slab2Number: 2,
    slab2From: 4,
    slab2To: 8,
    slab2Price: 11500,
    slab2Discount: 7.5,
    slab3Number: 3,
    slab3From: 9,
    slab3To: 15,
    slab3Price: 11000,
    slab3Discount: 10,
    slab4Number: 4,
    slab4From: 16,
    slab4To: 30,
    slab4Price: 10500,
    slab4Discount: 15,
  },
];

const mockExpenseCategories = [
  {
    id: 1,
    expenseCategoryCode: "EXP-001",
    expenseCategoryName: "Office Rent",
  },
  {
    id: 2,
    expenseCategoryCode: "EXP-002",
    expenseCategoryName: "Utilities",
  },
  {
    id: 3,
    expenseCategoryCode: "EXP-003",
    expenseCategoryName: "Salaries and Wages",
  },
  {
    id: 4,
    expenseCategoryCode: "EXP-004",
    expenseCategoryName: "Vehicle Maintenance",
  },
  {
    id: 5,
    expenseCategoryCode: "EXP-005",
    expenseCategoryName: "Office Supplies",
  },
  {
    id: 6,
    expenseCategoryCode: "EXP-006",
    expenseCategoryName: "Travel and Transportation",
  },
  {
    id: 7,
    expenseCategoryCode: "EXP-007",
    expenseCategoryName: "Insurance",
  },
  {
    id: 8,
    expenseCategoryCode: "EXP-008",
    expenseCategoryName: "Marketing and Advertising",
  },
  {
    id: 9,
    expenseCategoryCode: "EXP-009",
    expenseCategoryName: "Training and Development",
  },
  {
    id: 10,
    expenseCategoryCode: "EXP-010",
    expenseCategoryName: "IT Services and Software",
  },
  {
    id: 11,
    expenseCategoryCode: "EXP-011",
    expenseCategoryName: "Warehouse Expenses",
  },
  {
    id: 12,
    expenseCategoryCode: "EXP-012",
    expenseCategoryName: "Shipping and Freight",
  },
  {
    id: 13,
    expenseCategoryCode: "EXP-013",
    expenseCategoryName: "Equipment Rental",
  },
  {
    id: 14,
    expenseCategoryCode: "EXP-014",
    expenseCategoryName: "Professional Services",
  },
  {
    id: 15,
    expenseCategoryCode: "EXP-015",
    expenseCategoryName: "Bank Charges and Fees",
  },
];

const mockCustomerDiscountSlabs = [
  {
    id: 1,
    customerCode: "CUST001",
    customerName: "Royal Auto Center",
    active: true,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 10000,
    slab1Discount: 5,
    slab2Number: 2,
    slab2PriceFrom: 10001,
    slab2PriceTo: 25000,
    slab2Discount: 7.5,
    slab3Number: 3,
    slab3PriceFrom: 25001,
    slab3PriceTo: 50000,
    slab3Discount: 10,
    slab4Number: 4,
    slab4PriceFrom: 50001,
    slab4PriceTo: 100000,
    slab4Discount: 12.5,
    slab5Number: 5,
    slab5PriceFrom: 100001,
    slab5PriceTo: 500000,
    slab5Discount: 15,
  },
  {
    id: 2,
    customerCode: "CUST002",
    customerName: "Lanka Motors",
    active: true,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 15000,
    slab1Discount: 3,
    slab2Number: 2,
    slab2PriceFrom: 15001,
    slab2PriceTo: 30000,
    slab2Discount: 5,
    slab3Number: 3,
    slab3PriceFrom: 30001,
    slab3PriceTo: 75000,
    slab3Discount: 8,
    slab4Number: 4,
    slab4PriceFrom: 75001,
    slab4PriceTo: 150000,
    slab4Discount: 10,
    slab5Number: 5,
    slab5PriceFrom: 150001,
    slab5PriceTo: 750000,
    slab5Discount: 12,
  },
  {
    id: 3,
    customerCode: "CUST003",
    customerName: "Supreme Auto Parts",
    active: true,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 25000,
    slab1Discount: 8,
    slab2Number: 2,
    slab2PriceFrom: 25001,
    slab2PriceTo: 50000,
    slab2Discount: 10,
    slab3Number: 3,
    slab3PriceFrom: 50001,
    slab3PriceTo: 100000,
    slab3Discount: 12,
    slab4Number: 4,
    slab4PriceFrom: 100001,
    slab4PriceTo: 200000,
    slab4Discount: 15,
    slab5Number: 5,
    slab5PriceFrom: 200001,
    slab5PriceTo: 1000000,
    slab5Discount: 18,
  },
  {
    id: 4,
    customerCode: "CUST004",
    customerName: "Elite Car Care",
    active: false,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 5000,
    slab1Discount: 2,
    slab2Number: 2,
    slab2PriceFrom: 5001,
    slab2PriceTo: 15000,
    slab2Discount: 4,
    slab3Number: 3,
    slab3PriceFrom: 15001,
    slab3PriceTo: 30000,
    slab3Discount: 6,
    slab4Number: 4,
    slab4PriceFrom: 30001,
    slab4PriceTo: 75000,
    slab4Discount: 8,
    slab5Number: 5,
    slab5PriceFrom: 75001,
    slab5PriceTo: 300000,
    slab5Discount: 10,
  },
  {
    id: 5,
    customerCode: "CUST006",
    customerName: "Island Auto Imports",
    active: true,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 50000,
    slab1Discount: 10,
    slab2Number: 2,
    slab2PriceFrom: 50001,
    slab2PriceTo: 100000,
    slab2Discount: 12,
    slab3Number: 3,
    slab3PriceFrom: 100001,
    slab3PriceTo: 250000,
    slab3Discount: 15,
    slab4Number: 4,
    slab4PriceFrom: 250001,
    slab4PriceTo: 500000,
    slab4Discount: 17.5,
    slab5Number: 5,
    slab5PriceFrom: 500001,
    slab5PriceTo: 2000000,
    slab5Discount: 20,
  },
  {
    id: 6,
    customerCode: "CUST007",
    customerName: "Precision Auto Engineering",
    active: true,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 20000,
    slab1Discount: 5,
    slab2Number: 2,
    slab2PriceFrom: 20001,
    slab2PriceTo: 40000,
    slab2Discount: 7,
    slab3Number: 3,
    slab3PriceFrom: 40001,
    slab3PriceTo: 80000,
    slab3Discount: 9,
    slab4Number: 4,
    slab4PriceFrom: 80001,
    slab4PriceTo: 160000,
    slab4Discount: 11,
    slab5Number: 5,
    slab5PriceFrom: 160001,
    slab5PriceTo: 450000,
    slab5Discount: 13,
  },
  {
    id: 7,
    customerCode: "CUST008",
    customerName: "Green Light Motors",
    active: true,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 8000,
    slab1Discount: 3,
    slab2Number: 2,
    slab2PriceFrom: 8001,
    slab2PriceTo: 16000,
    slab2Discount: 5,
    slab3Number: 3,
    slab3PriceFrom: 16001,
    slab3PriceTo: 32000,
    slab3Discount: 7,
    slab4Number: 4,
    slab4PriceFrom: 32001,
    slab4PriceTo: 64000,
    slab4Discount: 9,
    slab5Number: 5,
    slab5PriceFrom: 64001,
    slab5PriceTo: 350000,
    slab5Discount: 11,
  },
  {
    id: 8,
    customerCode: "CUST009",
    customerName: "Highway Truck Services",
    active: true,
    slab1Number: 1,
    slab1PriceFrom: 0,
    slab1PriceTo: 30000,
    slab1Discount: 6,
    slab2Number: 2,
    slab2PriceFrom: 30001,
    slab2PriceTo: 60000,
    slab2Discount: 8,
    slab3Number: 3,
    slab3PriceFrom: 60001,
    slab3PriceTo: 120000,
    slab3Discount: 10,
    slab4Number: 4,
    slab4PriceFrom: 120001,
    slab4PriceTo: 240000,
    slab4Discount: 12,
    slab5Number: 5,
    slab5PriceFrom: 240001,
    slab5PriceTo: 800000,
    slab5Discount: 14,
  },
];

const mockItems = [
  {
    id: 1,
    // Item Details
    image: "spark_plug.jpg",
    itemCode: "ENG-SP-001",
    itemDescription: "Iridium Spark Plug - High Performance",
    classification: "Engine Parts",
    category: "Electronics",
    binLocation: "A-12-34",
    hsCodeNumber: "8511.10.00",
    itemWeight: 0.05,
    retailWholesale: "Both",
    description:
      "Premium quality iridium spark plug with extended lifespan and improved fuel efficiency. Compatible with most Japanese and European car models.",
    campaignItem: true,
    netItem: false,
    warrantyItem: true,

    // Inventory
    bufferStock: 50,
    reOrderQuantity: 100,
    reOrderLevelWS: 25,
    reOrderLevelRS: 15,
    wsQuantityInHand: 87,
    rsQuantityInHand: 43,
    wsQuantityOnOrder: 100,
    rsQuantityOnOrder: 50,
    receivedQuantity: 180,
    stockHoldDays: 60,
    minimumStockQuantity: 30,
    issuingQuantity: 10,
    minimumQuantity: 5,

    // Pricing
    profitMargin: 25,
    actualCost: 950,
    foreignCost: 850,
    localCost: 100,
    sellingPrice: 1250,
    agentSellingPrice: 1150,
    vatPercentage: 15,
    marketPrice: 1400,

    // Replacements
    replacePart1: "ENG-SP-002",
    replacePart2: "ENG-SP-003",
    replacePart3: "ENG-SP-004",
    duplicatePart1: "OEM-SP-001",
    duplicatePart2: "OEM-SP-002",
    duplicatePart3: "OEM-SP-003",

    // Additional
    currentMonthSalesWS: 130,
    currentMonthSalesRS: 75,
    qrCode: "QR-ENG-SP-001",
    size: 14,
    barCode: 8901234567890,
    leadTime1: 20,
    leadTime2: 30,
    leadTime3: 45,
  },
  {
    id: 2,
    // Item Details
    image: "oil_filter.jpg",
    itemCode: "ENG-OF-001",
    itemDescription: "Premium Oil Filter",
    classification: "Engine Parts",
    category: "Other",
    binLocation: "B-05-18",
    hsCodeNumber: "8421.23.00",
    itemWeight: 0.3,
    retailWholesale: "Both",
    description:
      "High-quality oil filter with superior filtration capability. Designed for extended use and compatible with synthetic and conventional oils.",
    campaignItem: false,
    netItem: false,
    warrantyItem: true,

    // Inventory
    bufferStock: 75,
    reOrderQuantity: 150,
    reOrderLevelWS: 40,
    reOrderLevelRS: 20,
    wsQuantityInHand: 120,
    rsQuantityInHand: 65,
    wsQuantityOnOrder: 150,
    rsQuantityOnOrder: 75,
    receivedQuantity: 225,
    stockHoldDays: 45,
    minimumStockQuantity: 35,
    issuingQuantity: 15,
    minimumQuantity: 10,

    // Pricing
    profitMargin: 35,
    actualCost: 450,
    foreignCost: 380,
    localCost: 70,
    sellingPrice: 650,
    agentSellingPrice: 600,
    vatPercentage: 15,
    marketPrice: 750,

    // Replacements
    replacePart1: "ENG-OF-002",
    replacePart2: "ENG-OF-003",
    replacePart3: "",
    duplicatePart1: "OEM-OF-001",
    duplicatePart2: "OEM-OF-002",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 180,
    currentMonthSalesRS: 95,
    qrCode: "QR-ENG-OF-001",
    size: 85,
    barCode: 8907654321098,
    leadTime1: 15,
    leadTime2: 25,
    leadTime3: 35,
  },
  {
    id: 3,
    // Item Details
    image: "brake_pad.jpg",
    itemCode: "BRK-PAD-001",
    itemDescription: "Ceramic Brake Pads (Front)",
    classification: "Other",
    category: "Other",
    binLocation: "C-08-22",
    hsCodeNumber: "8708.30.10",
    itemWeight: 1.2,
    retailWholesale: "Both",
    description:
      "Premium ceramic brake pads for front wheels. Provides superior stopping power with minimal noise and brake dust. Includes hardware kit.",
    campaignItem: true,
    netItem: true,
    warrantyItem: true,

    // Inventory
    bufferStock: 40,
    reOrderQuantity: 80,
    reOrderLevelWS: 20,
    reOrderLevelRS: 10,
    wsQuantityInHand: 65,
    rsQuantityInHand: 28,
    wsQuantityOnOrder: 80,
    rsQuantityOnOrder: 40,
    receivedQuantity: 120,
    stockHoldDays: 60,
    minimumStockQuantity: 20,
    issuingQuantity: 8,
    minimumQuantity: 4,

    // Pricing
    profitMargin: 30,
    actualCost: 2800,
    foreignCost: 2500,
    localCost: 300,
    sellingPrice: 3800,
    agentSellingPrice: 3500,
    vatPercentage: 15,
    marketPrice: 4200,

    // Replacements
    replacePart1: "BRK-PAD-002",
    replacePart2: "BRK-PAD-003",
    replacePart3: "BRK-PAD-004",
    duplicatePart1: "OEM-BRK-001",
    duplicatePart2: "OEM-BRK-002",
    duplicatePart3: "OEM-BRK-003",

    // Additional
    currentMonthSalesWS: 45,
    currentMonthSalesRS: 22,
    qrCode: "QR-BRK-PAD-001",
    size: 18,
    barCode: 8905678901234,
    leadTime1: 25,
    leadTime2: 40,
    leadTime3: 60,
  },
  {
    id: 4,
    // Item Details
    image: "air_filter.jpg",
    itemCode: "ENG-AF-001",
    itemDescription: "High-Flow Air Filter",
    classification: "Engine Parts",
    category: "Other",
    binLocation: "A-15-42",
    hsCodeNumber: "8421.31.00",
    itemWeight: 0.5,
    retailWholesale: "Both",
    description:
      "Performance high-flow air filter that increases horsepower while maintaining excellent filtration. Washable and reusable design.",
    campaignItem: true,
    netItem: false,
    warrantyItem: true,

    // Inventory
    bufferStock: 35,
    reOrderQuantity: 70,
    reOrderLevelWS: 20,
    reOrderLevelRS: 10,
    wsQuantityInHand: 48,
    rsQuantityInHand: 22,
    wsQuantityOnOrder: 70,
    rsQuantityOnOrder: 35,
    receivedQuantity: 105,
    stockHoldDays: 75,
    minimumStockQuantity: 25,
    issuingQuantity: 7,
    minimumQuantity: 5,

    // Pricing
    profitMargin: 40,
    actualCost: 1200,
    foreignCost: 1050,
    localCost: 150,
    sellingPrice: 1750,
    agentSellingPrice: 1600,
    vatPercentage: 15,
    marketPrice: 1900,

    // Replacements
    replacePart1: "ENG-AF-002",
    replacePart2: "ENG-AF-003",
    replacePart3: "",
    duplicatePart1: "OEM-AF-001",
    duplicatePart2: "",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 65,
    currentMonthSalesRS: 30,
    qrCode: "QR-ENG-AF-001",
    size: 30,
    barCode: 8903456789012,
    leadTime1: 20,
    leadTime2: 30,
    leadTime3: 45,
  },
  {
    id: 5,
    // Item Details
    image: "timing_belt.jpg",
    itemCode: "ENG-TB-001",
    itemDescription: "Complete Timing Belt Kit",
    classification: "Engine Parts",
    category: "Other",
    binLocation: "D-03-16",
    hsCodeNumber: "8409.91.00",
    itemWeight: 2.5,
    retailWholesale: "Both",
    description:
      "Complete timing belt kit including belt, tensioners, and water pump. Designed for precision timing and long service intervals.",
    campaignItem: false,
    netItem: true,
    warrantyItem: true,

    // Inventory
    bufferStock: 20,
    reOrderQuantity: 40,
    reOrderLevelWS: 10,
    reOrderLevelRS: 5,
    wsQuantityInHand: 28,
    rsQuantityInHand: 12,
    wsQuantityOnOrder: 40,
    rsQuantityOnOrder: 20,
    receivedQuantity: 60,
    stockHoldDays: 90,
    minimumStockQuantity: 15,
    issuingQuantity: 4,
    minimumQuantity: 2,

    // Pricing
    profitMargin: 25,
    actualCost: 6500,
    foreignCost: 6000,
    localCost: 500,
    sellingPrice: 8500,
    agentSellingPrice: 8000,
    vatPercentage: 15,
    marketPrice: 9200,

    // Replacements
    replacePart1: "ENG-TB-002",
    replacePart2: "",
    replacePart3: "",
    duplicatePart1: "OEM-TB-001",
    duplicatePart2: "OEM-TB-002",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 18,
    currentMonthSalesRS: 8,
    qrCode: "QR-ENG-TB-001",
    size: 42,
    barCode: 8901234509876,
    leadTime1: 35,
    leadTime2: 50,
    leadTime3: 70,
  },
  {
    id: 6,
    // Item Details
    image: "radiator.jpg",
    itemCode: "COOL-RAD-001",
    itemDescription: "Aluminum Performance Radiator",
    classification: "Other",
    category: "Other",
    binLocation: "E-09-26",
    hsCodeNumber: "8708.91.00",
    itemWeight: 4.8,
    retailWholesale: "Wholesale",
    description:
      "All-aluminum performance radiator with improved cooling capacity. Direct replacement for OEM radiator with superior thermal efficiency.",
    campaignItem: false,
    netItem: false,
    warrantyItem: true,

    // Inventory
    bufferStock: 15,
    reOrderQuantity: 25,
    reOrderLevelWS: 8,
    reOrderLevelRS: 0,
    wsQuantityInHand: 18,
    rsQuantityInHand: 0,
    wsQuantityOnOrder: 25,
    rsQuantityOnOrder: 0,
    receivedQuantity: 25,
    stockHoldDays: 120,
    minimumStockQuantity: 10,
    issuingQuantity: 2,
    minimumQuantity: 1,

    // Pricing
    profitMargin: 20,
    actualCost: 12500,
    foreignCost: 11800,
    localCost: 700,
    sellingPrice: 15500,
    agentSellingPrice: 14800,
    vatPercentage: 15,
    marketPrice: 16800,

    // Replacements
    replacePart1: "COOL-RAD-002",
    replacePart2: "",
    replacePart3: "",
    duplicatePart1: "OEM-RAD-001",
    duplicatePart2: "",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 10,
    currentMonthSalesRS: 0,
    qrCode: "QR-COOL-RAD-001",
    size: 65,
    barCode: 8907890123456,
    leadTime1: 45,
    leadTime2: 60,
    leadTime3: 90,
  },
  {
    id: 7,
    // Item Details
    image: "fuel_pump.jpg",
    itemCode: "FUEL-PMP-001",
    itemDescription: "Electric Fuel Pump Assembly",
    classification: "Engine Parts",
    category: "Electronics",
    binLocation: "B-22-38",
    hsCodeNumber: "8413.30.00",
    itemWeight: 1.3,
    retailWholesale: "Both",
    description:
      "Complete in-tank electric fuel pump assembly with pressure regulator. Direct OEM replacement with improved reliability and flow rate.",
    campaignItem: false,
    netItem: true,
    warrantyItem: true,

    // Inventory
    bufferStock: 25,
    reOrderQuantity: 40,
    reOrderLevelWS: 15,
    reOrderLevelRS: 8,
    wsQuantityInHand: 32,
    rsQuantityInHand: 14,
    wsQuantityOnOrder: 40,
    rsQuantityOnOrder: 20,
    receivedQuantity: 60,
    stockHoldDays: 90,
    minimumStockQuantity: 20,
    issuingQuantity: 5,
    minimumQuantity: 3,

    // Pricing
    profitMargin: 30,
    actualCost: 8900,
    foreignCost: 8200,
    localCost: 700,
    sellingPrice: 12000,
    agentSellingPrice: 11200,
    vatPercentage: 15,
    marketPrice: 13500,

    // Replacements
    replacePart1: "FUEL-PMP-002",
    replacePart2: "FUEL-PMP-003",
    replacePart3: "",
    duplicatePart1: "OEM-FP-001",
    duplicatePart2: "OEM-FP-002",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 22,
    currentMonthSalesRS: 10,
    qrCode: "QR-FUEL-PMP-001",
    size: 28,
    barCode: 8905432109876,
    leadTime1: 30,
    leadTime2: 45,
    leadTime3: 60,
  },
  {
    id: 8,
    // Item Details
    image: "alternator.jpg",
    itemCode: "ELEC-ALT-001",
    itemDescription: "High Output Alternator",
    classification: "Engine Parts",
    category: "Electronics",
    binLocation: "C-18-44",
    hsCodeNumber: "8511.50.00",
    itemWeight: 5.2,
    retailWholesale: "Wholesale",
    description:
      "High output alternator rated at 220 amp. Perfect for vehicles with upgraded audio systems or additional electrical accessories.",
    campaignItem: false,
    netItem: false,
    warrantyItem: true,

    // Inventory
    bufferStock: 12,
    reOrderQuantity: 20,
    reOrderLevelWS: 6,
    reOrderLevelRS: 0,
    wsQuantityInHand: 15,
    rsQuantityInHand: 0,
    wsQuantityOnOrder: 20,
    rsQuantityOnOrder: 0,
    receivedQuantity: 20,
    stockHoldDays: 150,
    minimumStockQuantity: 8,
    issuingQuantity: 2,
    minimumQuantity: 1,

    // Pricing
    profitMargin: 25,
    actualCost: 15800,
    foreignCost: 15000,
    localCost: 800,
    sellingPrice: 20500,
    agentSellingPrice: 19500,
    vatPercentage: 15,
    marketPrice: 22000,

    // Replacements
    replacePart1: "ELEC-ALT-002",
    replacePart2: "",
    replacePart3: "",
    duplicatePart1: "OEM-ALT-001",
    duplicatePart2: "",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 8,
    currentMonthSalesRS: 0,
    qrCode: "QR-ELEC-ALT-001",
    size: 35,
    barCode: 8909876543210,
    leadTime1: 40,
    leadTime2: 60,
    leadTime3: 90,
  },
  {
    id: 9,
    // Item Details
    image: "suspension_kit.jpg",
    itemCode: "SUSP-KIT-001",
    itemDescription: "Complete Suspension Kit",
    classification: "Other",
    category: "Other",
    binLocation: "F-05-28",
    hsCodeNumber: "8708.80.00",
    itemWeight: 18.5,
    retailWholesale: "Wholesale",
    description:
      "Complete suspension kit including struts, springs, and mounting hardware. Sport-tuned for improved handling while maintaining ride comfort.",
    campaignItem: true,
    netItem: true,
    warrantyItem: true,

    // Inventory
    bufferStock: 8,
    reOrderQuantity: 12,
    reOrderLevelWS: 4,
    reOrderLevelRS: 0,
    wsQuantityInHand: 10,
    rsQuantityInHand: 0,
    wsQuantityOnOrder: 12,
    rsQuantityOnOrder: 0,
    receivedQuantity: 12,
    stockHoldDays: 180,
    minimumStockQuantity: 5,
    issuingQuantity: 1,
    minimumQuantity: 1,

    // Pricing
    profitMargin: 20,
    actualCost: 45000,
    foreignCost: 42500,
    localCost: 2500,
    sellingPrice: 56000,
    agentSellingPrice: 53000,
    vatPercentage: 15,
    marketPrice: 62000,

    // Replacements
    replacePart1: "SUSP-KIT-002",
    replacePart2: "",
    replacePart3: "",
    duplicatePart1: "OEM-SUSP-001",
    duplicatePart2: "",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 5,
    currentMonthSalesRS: 0,
    qrCode: "QR-SUSP-KIT-001",
    size: 90,
    barCode: 8902468135790,
    leadTime1: 60,
    leadTime2: 90,
    leadTime3: 120,
  },
  {
    id: 10,
    // Item Details
    image: "clutch_kit.jpg",
    itemCode: "TRANS-CL-001",
    itemDescription: "Heavy Duty Clutch Kit",
    classification: "Other",
    category: "Other",
    binLocation: "D-12-36",
    hsCodeNumber: "8708.93.00",
    itemWeight: 8.7,
    retailWholesale: "Both",
    description:
      "Heavy-duty clutch kit with pressure plate, disc, release bearing, and alignment tool. Rated for up to 30% increased torque capacity over OEM.",
    campaignItem: false,
    netItem: true,
    warrantyItem: true,

    // Inventory
    bufferStock: 15,
    reOrderQuantity: 25,
    reOrderLevelWS: 8,
    reOrderLevelRS: 4,
    wsQuantityInHand: 20,
    rsQuantityInHand: 7,
    wsQuantityOnOrder: 25,
    rsQuantityOnOrder: 10,
    receivedQuantity: 35,
    stockHoldDays: 120,
    minimumStockQuantity: 10,
    issuingQuantity: 2,
    minimumQuantity: 1,

    // Pricing
    profitMargin: 25,
    actualCost: 18500,
    foreignCost: 17500,
    localCost: 1000,
    sellingPrice: 24000,
    agentSellingPrice: 22500,
    vatPercentage: 15,
    marketPrice: 26500,

    // Replacements
    replacePart1: "TRANS-CL-002",
    replacePart2: "TRANS-CL-003",
    replacePart3: "",
    duplicatePart1: "OEM-CL-001",
    duplicatePart2: "OEM-CL-002",
    duplicatePart3: "",

    // Additional
    currentMonthSalesWS: 12,
    currentMonthSalesRS: 5,
    qrCode: "QR-TRANS-CL-001",
    size: 48,
    barCode: 8901357924680,
    leadTime1: 35,
    leadTime2: 50,
    leadTime3: 75,
  },
];

export const fetchCompanies = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockCompanies;
  }

  return mockCompanies.filter(
    (company) =>
      company.companyName.toLowerCase().includes(query.toLowerCase()) ||
      company.companyCode.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchCustomers = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockCustomers;
  }

  return mockCustomers.filter(
    (customer) =>
      customer.customerName.toLowerCase().includes(query.toLowerCase()) ||
      customer.customerCode.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchSuppliers = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockSuppliers;
  }

  return mockSuppliers.filter(
    (supplier) =>
      supplier.supplierName.toLowerCase().includes(query.toLowerCase()) ||
      supplier.supplierCode.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchBanks = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockBanks;
  }

  return mockBanks.filter(
    (bank) =>
      bank.bankName.toLowerCase().includes(query.toLowerCase()) ||
      bank.bankCode.toLowerCase().includes(query.toLowerCase()) ||
      bank.branchName.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchBranches = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockBranches;
  }

  return mockBranches.filter(
    (branch) =>
      branch.branchName.toLowerCase().includes(query.toLowerCase()) ||
      branch.branchCode.toLowerCase().includes(query.toLowerCase()) ||
      branch.city.toLowerCase().includes(query.toLowerCase()) ||
      branch.district.toLowerCase().includes(query.toLowerCase()) ||
      branch.bankCode.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchLocations = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockLocations;
  }

  return mockLocations.filter(
    (location) =>
      location.locationCode.toLowerCase().includes(query.toLowerCase()) ||
      location.description.toLowerCase().includes(query.toLowerCase()) ||
      location.type.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchAreas = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockAreas;
  }

  return mockAreas.filter(
    (area) =>
      area.areaCode.toLowerCase().includes(query.toLowerCase()) ||
      area.areaName.toLowerCase().includes(query.toLowerCase()) ||
      area.cityName.toLowerCase().includes(query.toLowerCase()) ||
      area.routeCode.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchRoutes = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockRoutes;
  }

  return mockRoutes.filter(
    (route) =>
      route.routeCode.toLowerCase().includes(query.toLowerCase()) ||
      route.description.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchUtilities = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockUtilities;
  }

  return mockUtilities.filter(
    (utility) =>
      utility.expenseReferenceNumber
        .toLowerCase()
        .includes(query.toLowerCase()) ||
      utility.expenseCode.toLowerCase().includes(query.toLowerCase()) ||
      utility.description.toLowerCase().includes(query.toLowerCase()) ||
      utility.period.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchTransportAgents = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockTransportAgents;
  }

  return mockTransportAgents.filter(
    (agent) =>
      agent.agentCode.toLowerCase().includes(query.toLowerCase()) ||
      agent.agentName.toLowerCase().includes(query.toLowerCase()) ||
      agent.contactName.toLowerCase().includes(query.toLowerCase()) ||
      agent.address.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchHSCodes = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockHSCodes;
  }

  return mockHSCodes.filter(
    (hsCode) =>
      hsCode.item.toLowerCase().includes(query.toLowerCase()) ||
      hsCode.itemDescription.toLowerCase().includes(query.toLowerCase()) ||
      hsCode.hsCodeNumber.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchCategories = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockCategories;
  }

  return mockCategories.filter(
    (category) =>
      category.categoryCode.toLowerCase().includes(query.toLowerCase()) ||
      category.categoryDescription.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchClassifications = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockClassifications;
  }

  return mockClassifications.filter(
    (classification) =>
      classification.classificationCode
        .toLowerCase()
        .includes(query.toLowerCase()) ||
      classification.classificationDescription
        .toLowerCase()
        .includes(query.toLowerCase())
  );
};

export const fetchReasonRemarks = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockReasonRemarks;
  }

  return mockReasonRemarks.filter(
    (reasonRemark) =>
      reasonRemark.reasonRemarkCode
        .toLowerCase()
        .includes(query.toLowerCase()) ||
      reasonRemark.description.toLowerCase().includes(query.toLowerCase()) ||
      reasonRemark.category.toLowerCase().includes(query.toLowerCase()) ||
      reasonRemark.type.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchSalesReps = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockSalesReps;
  }

  return mockSalesReps.filter(
    (rep) =>
      rep.repCode.toLowerCase().includes(query.toLowerCase()) ||
      rep.repName.toLowerCase().includes(query.toLowerCase()) ||
      rep.acCode.toLowerCase().includes(query.toLowerCase()) ||
      rep.acName.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchShopReps = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockShopReps;
  }

  return mockShopReps.filter(
    (shopRep) =>
      shopRep.repCode.toLowerCase().includes(query.toLowerCase()) ||
      shopRep.shopRepCode.toLowerCase().includes(query.toLowerCase()) ||
      shopRep.shopRepName.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchItemWholeSaleSlabs = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockItemWholeSaleSlabs;
  }

  return mockItemWholeSaleSlabs.filter(
    (item) =>
      item.itemCode.toLowerCase().includes(query.toLowerCase()) ||
      item.itemDescription.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchExpenseCategories = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockExpenseCategories;
  }

  return mockExpenseCategories.filter(
    (category) =>
      category.expenseCategoryCode
        .toLowerCase()
        .includes(query.toLowerCase()) ||
      category.expenseCategoryName.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchCustomerDiscountSlabs = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockCustomerDiscountSlabs;
  }

  return mockCustomerDiscountSlabs.filter(
    (slab) =>
      slab.customerName.toLowerCase().includes(query.toLowerCase()) ||
      slab.customerCode.toLowerCase().includes(query.toLowerCase())
  );
};

export const fetchItems = async (query = "") => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return mockItems;
  }

  return mockItems.filter(
    (item) =>
      item.itemCode.toLowerCase().includes(query.toLowerCase()) ||
      item.itemDescription.toLowerCase().includes(query.toLowerCase()) ||
      item.classification.toLowerCase().includes(query.toLowerCase()) ||
      item.category.toLowerCase().includes(query.toLowerCase())
  );
};
